In [22]:
print("everything will be ok, BUDDY")

everything will be ok, BUDDY

In [23]:
!pip install numpy as np
!pip install pandas as pd
!pip install matplotlib.pyplot as plt
!pip install seaborn as sns
!pip install plotly as py
!pip install cufflinks 
!pip install plotly
!pip install inltk
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /home/ihtgoot/.local/lib/python3.10/site-packages (1.26.4)
ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/ihtgoot/.local/lib/python3.10/site-packages (2.2.3)
ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement matplotlib.pyplot (from versions: none)
ERROR: No matching distribution found for matplotlib.pyplot
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in /home/ihtgoot/.local/lib/python3.10/site-packages (0.13.2)
ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in /home/ihtgoot/.local/lib/python3.10/site-packages (4.14.3)
ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cufflinks in /home/ihtgoot/.local/lib/python3.10/site-packages (0.17.3)
Requirement already satisfied: colorlover>=0.2.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from cufflinks) (0.3.0)
Requirement already satisfied: ipython>=5.3.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from cufflinks) (8.37.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from cufflinks) (8.1.8)
Requirement already satisfied: numpy>=1.9.2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from cufflinks) (1.26.4)
Requirement already satisfied: pandas>=0.19.2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from cufflinks) (2.2.3)
Requirement already satisfied: plotly>=4.1.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from cufflinks) (4.14.3)
Requirement already satisfied: setuptools>=34.4.1 in /usr/lib/python3/dist-packages (from cufflinks) (59.6.0)
Requirement already satisfied: six>=1.9.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from cufflinks) (1.17.0)
Requirement already satisfied: decorator in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (5.2.1)
Requirement already satisfied: exceptiongroup in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (1.3.0)
Requirement already satisfied: jedi>=0.16 in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (0.19.2)
Requirement already satisfied: matplotlib-inline in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (2.19.2)
Requirement already satisfied: stack_data in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (5.14.3)
Requirement already satisfied: typing_extensions>=4.6 in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipython>=5.3.0->cufflinks) (4.15.0)
Requirement already satisfied: wcwidth in /home/ihtgoot/.local/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->cufflinks) (0.2.14)
Requirement already satisfied: comm>=0.1.3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipywidgets>=7.0.0->cufflinks) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /home/ihtgoot/.local/lib/python3.10/site-packages (from ipywidgets>=7.0.0->cufflinks) (3.0.16)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/ihtgoot/.local/lib/python3.10/site-packages (from jedi>=0.16->ipython>=5.3.0->cufflinks) (0.8.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from pandas>=0.19.2->cufflinks) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from pandas>=0.19.2->cufflinks) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/ihtgoot/.local/lib/python3.10/site-packages (from pandas>=0.19.2->cufflinks) (2025.2)
Requirement already satisfied: ptyprocess>=0.5 in /home/ihtgoot/.local/lib/python3.10/site-packages (from pexpect>4.3->ipython>=5.3.0->cufflinks) (0.7.0)
Requirement already satisfied: retrying>=1.3.3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from plotly>=4.1.1->cufflinks) (1.4.2)
Requirement already satisfied: executing>=1.2.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from stack_data->ipython>=5.3.0->cufflinks) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from stack_data->ipython>=5.3.0->cufflinks) (3.0.0)
Requirement already satisfied: pure-eval in /home/ihtgoot/.local/lib/python3.10/site-packages (from stack_data->ipython>=5.3.0->cufflinks) (0.2.3)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in /home/ihtgoot/.local/lib/python3.10/site-packages (4.14.3)
Requirement already satisfied: retrying>=1.3.3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from plotly) (1.4.2)
Requirement already satisfied: six in /home/ihtgoot/.local/lib/python3.10/site-packages (from plotly) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: inltk in /home/ihtgoot/.local/lib/python3.10/site-packages (0.9)
Requirement already satisfied: aiohttp>=3.5.4 in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (3.13.2)
Requirement already satisfied: async-timeout>=3.0.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (5.0.1)
Requirement already satisfied: Pillow in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (12.0.0)
Requirement already satisfied: beautifulsoup4 in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (4.14.2)
Requirement already satisfied: bottleneck in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (1.6.0)
Requirement already satisfied: fastprogress>=0.1.19 in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (1.0.3)
Requirement already satisfied: matplotlib in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (3.10.7)
Requirement already satisfied: numexpr in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (2.14.1)
Requirement already satisfied: numpy>=1.15 in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (1.26.4)
Requirement already satisfied: nvidia-ml-py3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (7.352.0)
Requirement already satisfied: packaging in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (25.0)
Requirement already satisfied: pandas in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (2.2.3)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from inltk) (5.4.1)
Requirement already satisfied: requests in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (2.32.5)
Requirement already satisfied: scipy in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (1.13.1)
Requirement already satisfied: spacy>=2.0.18 in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (3.8.8)
Requirement already satisfied: typing in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (3.7.4.3)
Requirement already satisfied: fastai==1.0.57 in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (1.0.57)
Requirement already satisfied: sentencepiece in /home/ihtgoot/.local/lib/python3.10/site-packages (from inltk) (0.0.0)
Requirement already satisfied: torch>=1.0.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from fastai==1.0.57->inltk) (2.8.0)
Requirement already satisfied: torchvision in /home/ihtgoot/.local/lib/python3.10/site-packages (from fastai==1.0.57->inltk) (0.23.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from aiohttp>=3.5.4->inltk) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from aiohttp>=3.5.4->inltk) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from aiohttp>=3.5.4->inltk) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from aiohttp>=3.5.4->inltk) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/ihtgoot/.local/lib/python3.10/site-packages (from aiohttp>=3.5.4->inltk) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from aiohttp>=3.5.4->inltk) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from aiohttp>=3.5.4->inltk) (1.22.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from multidict<7.0,>=4.5->aiohttp>=3.5.4->inltk) (4.15.0)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.17.0->aiohttp>=3.5.4->inltk) (3.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (8.3.8)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (0.4.2)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (4.67.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (2.11.9)
Requirement already satisfied: jinja2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from spacy>=2.0.18->inltk) (3.1.6)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from spacy>=2.0.18->inltk) (59.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=2.0.18->inltk) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=2.0.18->inltk) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=2.0.18->inltk) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from requests->inltk) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from requests->inltk) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /home/ihtgoot/.local/lib/python3.10/site-packages (from requests->inltk) (2025.8.3)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy>=2.0.18->inltk) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from thinc<8.4.0,>=8.3.4->spacy>=2.0.18->inltk) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy>=2.0.18->inltk) (8.2.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from weasel<0.5.0,>=0.4.2->spacy>=2.0.18->inltk) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from weasel<0.5.0,>=0.4.2->spacy>=2.0.18->inltk) (7.5.0)
Requirement already satisfied: wrapt in /home/ihtgoot/.local/lib/python3.10/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy>=2.0.18->inltk) (1.17.3)
Requirement already satisfied: filelock in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (3.19.1)
Requirement already satisfied: sympy>=1.13.3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (1.14.0)
Requirement already satisfied: networkx in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (3.4.2)
Requirement already satisfied: fsspec in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (2025.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from torch>=1.0.0->fastai==1.0.57->inltk) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from sympy>=1.13.3->torch>=1.0.0->fastai==1.0.57->inltk) (1.3.0)
Requirement already satisfied: soupsieve>1.2 in /home/ihtgoot/.local/lib/python3.10/site-packages (from beautifulsoup4->inltk) (2.8)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from jinja2->spacy>=2.0.18->inltk) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from matplotlib->inltk) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /home/ihtgoot/.local/lib/python3.10/site-packages (from matplotlib->inltk) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/ihtgoot/.local/lib/python3.10/site-packages (from matplotlib->inltk) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from matplotlib->inltk) (1.4.9)
Requirement already satisfied: pyparsing>=3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from matplotlib->inltk) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /home/ihtgoot/.local/lib/python3.10/site-packages (from matplotlib->inltk) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/ihtgoot/.local/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->inltk) (1.17.0)
Requirement already satisfied: pytz>=2020.1 in /home/ihtgoot/.local/lib/python3.10/site-packages (from pandas->inltk) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/ihtgoot/.local/lib/python3.10/site-packages (from pandas->inltk) (2025.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in /home/ihtgoot/.local/lib/python3.10/site-packages (3.9.2)
Requirement already satisfied: click in /home/ihtgoot/.local/lib/python3.10/site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /home/ihtgoot/.local/lib/python3.10/site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /home/ihtgoot/.local/lib/python3.10/site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /home/ihtgoot/.local/lib/python3.10/site-packages (from nltk) (4.67.1)

In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as py
import cufflinks as cf
from plotly.offline import iplot
import inltk
import nltk
%matplotlib inline

In [2]:
py.offline.init_notebook_mode(connected=True)
cf.go_offline()

In [10]:
df = pd.read_csv('punjabi.txt',sep="\n")

ValueError: Specified \n as separator or delimiter. This forces the python engine which does not accept a line terminator. Hence it is not allowed to use the line terminator as separator.

In [33]:
df.head(1)

Empty DataFrame
Columns: []
Index: [
ਵੱਡਾ (ਬੇਓਨਸੇ ਗੀਤ)

"ਵੱਡਾ" (ਵੱਡੇ ਅੱਖਰ ਵਿੱਚ ਸ਼ੈਲੀਬੱਧ) ਅਮਰੀਕੀ ਗਾਇਕ ਬਿਓਨਸੇ ਦੁਆਰਾ 2019 ਦੀ ਐਲਬਮ "" ਤੋਂ ਇੱਕ ਗੀਤ ਹੈ ਅਤੇ 2020 ਦੀ ਫਿਲਮ "" ਬਲੈਕ ਇਜ਼ ਕਿੰਗ "" ਵਿੱਚ ਪ੍ਰਦਰਸ਼ਿਤ ਕੀਤਾ ਗਿਆ ਹੈ।
ਪਿਛੋਕਡ਼.
ਇਹ ਗੀਤ ਬਿਓਨਸੇ ਦੇ ਸਟੂਡੀਓ ਵਿੱਚ ਇੱਕ ਲਿਖਣ ਕੈਂਪ ਵਿੱਚ ਲਿਖਿਆ ਗਿਆ ਸੀ ਅਤੇ ਬ੍ਰਿਟਿਸ਼ ਗਾਇਕ-ਗੀਤਕਾਰ ਰੇਅ ਅਤੇ ਯੂ. ਐੱਸ. ਗੀਤਕਾਰ ਸਟੇਸੀ ਬਾਰਥੇ ਨਾਲ ਇੱਕ ਬੰਧਨ ਦੇ ਕਾਰਨ ਬਣਾਇਆ ਗਿਆ ਸੀ। ਰੇ ਨੇ ਬੀਬੀਸੀ ਨਿਊਜ਼ਬੀਟ ਨੂੰ ਦੱਸਿਆਃ "ਮੈਨੂੰ ਯਾਦ ਹੈ ਕਿ ਅਸੀਂ ਦੋਵੇਂ ਸੱਚਮੁੱਚ ਇੱਕ ਹਨੇਰੇ, ਉਦਾਸ ਜਗ੍ਹਾ ਵਿੱਚ ਸੀ ਅਤੇ ਅਸੀਂ ਆਪਣੇ ਆਪ ਨੂੰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਉਣ ਲਈ ਕੁਝ ਬਣਾਉਣਾ ਚਾਹੁੰਦੇ ਸੀ। ਅਸੀਂ ਸ਼ਾਇਦ ਦੋ ਜਾਂ ਤਿੰਨ ਘੰਟੇ ਇਸ ਉੱਤੇ ਬਿਤਾਏ। ਇਹ 3 ਏ ਸੀ।ਐਮ. ਅਤੇ ਮੈਨੂੰ ਯਾਦ ਹੈ ਕਿ ਬਿਓਨਸੇ ਦੀ ਟੀਮ ਆਈ ਅਤੇ ਸੁਣਿਆ ਕਿ ਅਸੀਂ ਹੁਣ ਤੱਕ ਕੀ ਬਣਾਇਆ ਹੈ ਅਤੇ ਪੂਰੀ ਤਰ੍ਹਾਂ ਘਬਰਾ ਗਏ ਹਾਂ। ਇਹ ਸ਼ਾਨਦਾਰ ਸੀ।"ਰੇ ਨੇ ਅਧਿਕਾਰਤ ਚਾਰਟ ਨੂੰ ਇਹ ਵੀ ਦੱਸਿਆਃ" ਮੈਂ ਬਹੁਤ ਸਾਰੇ ਗੀਤ ਲਿਖੇ-ਮੈਂ ਇੱਕ ਸ਼ਿਫਟ ਵਿੱਚ ਪਾ ਦਿੱਤਾ। ਪਰ [ਬੇਓਨਸੇ] ਨੂੰ ਵੱਡੇ ਨਾਲ ਪਿਆਰ ਹੋ ਗਿਆ।"ਬਿਓਨਸੇ ਨੇ ਰੇਅ ਨੂੰ ਦੱਸਿਆ ਕਿ 2019 ਦੇ" "ਦਿ ਲਾਇਨ ਕਿੰਗ" "ਯੂਰਪੀਅਨ ਪ੍ਰੀਮੀਅਰ ਵਿੱਚ ਐਲਬਮ ਦਾ ਪਹਿਲਾ ਗੀਤ" "ਵੱਡਾ" "ਹੋਵੇਗਾ, ਅਤੇ ਜਿਵੇਂ ਕਿ ਵੀਡੀਓ ਵਿੱਚ ਫਡ਼ਿਆ ਗਿਆ ਹੈ, ਉਸ ਦੀ ਪ੍ਰਤੀਕਿਰਿਆ ਵਾਇਰਲ ਹੋ ਗਈ। ਰੇ ਨੇ ਟਵੀਟ ਕੀਤਾ, "ਬਿਓਨਸੇ ਨੇ ਮੈਨੂੰ ਦੱਸਿਆ ਕਿ ਮੈਂ ਨਵੀਂ ਐਲਬਮ 'ਤੇ ਟਰੈਕ 1 ਲਿਖਿਆ ਹੈ।.. ਇਸ ਨੂੰ ਵੱਡਾ ਕਿਹਾ ਜਾਂਦਾ ਹੈ। ਮੈਂ ਨਹੀਂ ਕਰ ਸਕਦਾ।"
ਰਚਨਾ ਅਤੇ ਗੀਤਾਂ ਦੀ ਵਿਆਖਿਆ।
"ਵੱਡਾ" ਤੋਂ ਪਹਿਲਾਂ "ਸੰਤੁਲਨ" ਹੈ, ਇੱਕ ਮੁਫਾਸਾ ਇੰਟਰਲੂਡ ਜਿਸ ਨੂੰ ਜੇਮਜ਼ ਅਰਲ ਜੋਨਜ਼ ਦੁਆਰਾ ਆਵਾਜ਼ ਦਿੱਤੀ ਗਈ ਹੈ, ਜੋ 2019 ਦੀ ਫਿਲਮ ਤੋਂ ਉਸ ਦੇ "ਜੀਵਨ ਦੇ ਚੱਕਰ" ਭਾਸ਼ਣ ਦਾ ਨਮੂਨਾ ਹੈ। ਦੋਵੇਂ ਟਰੈਕ ਇੱਕ ਦੂਜੇ ਵਿੱਚ ਵੱਜਦੇ ਹਨ। "ਡੈਜ਼ਡ" ਨੇ ਇਸ ਤਬਦੀਲੀ ਨੂੰ "ਟਰੈਕ ਦੇ ਬੋਲਾਂ ਨਾਲ ਚੰਗੀ ਤਰ੍ਹਾਂ ਬੰਨ੍ਹਣਾ" ਦੱਸਿਆ।"" "ਅਟਲਾਂਟਿਕ" "ਦੇ ਅਨੁਸਾਰ," "ਵੱਡੇ" "ਵਿੱਚ" "ਸ਼ਾਹੀ ਉੱਤਰਾਧਿਕਾਰੀ" "ਦਾ ਇੱਕ ਵਿਆਪਕ ਵਿਸ਼ਾ ਹੈ ਅਤੇ ਨਾਲ ਹੀ" "ਜੀਵਨ ਦੇ ਚੱਕਰ ਦੇ" "ਵਾਤਾਵਰਣ ਅਤੇ ਹੋਂਦ" "ਪਹਿਲੂਆਂ ਦੀ ਇੱਕ ਅੰਡਰਕਰੰਟ ਖੋਜ ਹੈ।"ਮੈਟਜ਼ਾਵ ਸਮੀਖਿਆ ਨੇ" "ਵੱਡੇ" "ਨੂੰ" "ਅਫ਼ਰੀਕੀ ਮਹਾਂਦੀਪ ਦੀ ਕੁਦਰਤੀ ਦੌਲਤ ਲਈ ਇੱਕ ਸਨਮਾਨ" "ਵਜੋਂ ਦਰਸਾਇਆ, ਜਦੋਂ ਕਿ ਬੇਯੋੰਸੇ ਦੇ ਬੱਚਿਆਂ ਨੂੰ ਸ਼ਰਧਾਂਜਲੀ ਵਜੋਂ ਵੀ ਕੰਮ ਕੀਤਾ, ਉਹਨਾਂ ਨੂੰ ਸਮੂਹਕ ਗਿਆਨ ਦੀ ਵਿਆਖਿਆ ਸ਼ਕਤੀ ਨੂੰ ਦਰਸਾਉਂਦਾ ਹੈ।"
ਸੰਗੀਤ ਵੀਡੀਓ.
ਇੱਕ ਸੰਗੀਤ ਵੀਡੀਓ 19 ਜੁਲਾਈ, 2019 ਨੂੰ ਜਾਰੀ ਕੀਤਾ ਗਿਆ ਸੀ, ਜੋ ਕਿ ਐਲਬਮ ਦੇ ਮੁੱਖ ਸਿੰਗਲ "ਸਪਿਰਟ" ਦੇ ਸੰਗੀਤ ਵੀਡੀਓ ਦੇ ਵਿਸਤ੍ਰਿਤ ਸੰਸਕਰਣ ਦੇ ਦੂਜੇ ਹਿੱਸੇ ਵਜੋਂ ਸੀ।
ਇੱਕ ਦੂਜਾ ਸੰਗੀਤ ਵੀਡੀਓ "ਬਲੈਕ ਇਜ਼ ਕਿੰਗ" ਵਿੱਚ ਜਾਰੀ ਕੀਤਾ ਗਿਆ ਸੀ। ਇਸ ਵਿੱਚ ਮੂਲ ਵੀਡੀਓ ਦੇ ਹਿੱਸੇ ਹਨ ਜਿਨ੍ਹਾਂ ਵਿੱਚ ਵਿਸ਼ੇਸ਼ ਤੌਰ ਉੱਤੇ ਫਿਲਮ ਲਈ ਬਣਾਈ ਗਈ ਨਵੀਂ ਫੁਟੇਜ ਹੈ।

]

In [37]:
df.isnull()

Empty DataFrame
Columns: []
Index: [
ਵੱਡਾ (ਬੇਓਨਸੇ ਗੀਤ)

"ਵੱਡਾ" (ਵੱਡੇ ਅੱਖਰ ਵਿੱਚ ਸ਼ੈਲੀਬੱਧ) ਅਮਰੀਕੀ ਗਾਇਕ ਬਿਓਨਸੇ ਦੁਆਰਾ 2019 ਦੀ ਐਲਬਮ "" ਤੋਂ ਇੱਕ ਗੀਤ ਹੈ ਅਤੇ 2020 ਦੀ ਫਿਲਮ "" ਬਲੈਕ ਇਜ਼ ਕਿੰਗ "" ਵਿੱਚ ਪ੍ਰਦਰਸ਼ਿਤ ਕੀਤਾ ਗਿਆ ਹੈ।
ਪਿਛੋਕਡ਼.
ਇਹ ਗੀਤ ਬਿਓਨਸੇ ਦੇ ਸਟੂਡੀਓ ਵਿੱਚ ਇੱਕ ਲਿਖਣ ਕੈਂਪ ਵਿੱਚ ਲਿਖਿਆ ਗਿਆ ਸੀ ਅਤੇ ਬ੍ਰਿਟਿਸ਼ ਗਾਇਕ-ਗੀਤਕਾਰ ਰੇਅ ਅਤੇ ਯੂ. ਐੱਸ. ਗੀਤਕਾਰ ਸਟੇਸੀ ਬਾਰਥੇ ਨਾਲ ਇੱਕ ਬੰਧਨ ਦੇ ਕਾਰਨ ਬਣਾਇਆ ਗਿਆ ਸੀ। ਰੇ ਨੇ ਬੀਬੀਸੀ ਨਿਊਜ਼ਬੀਟ ਨੂੰ ਦੱਸਿਆਃ "ਮੈਨੂੰ ਯਾਦ ਹੈ ਕਿ ਅਸੀਂ ਦੋਵੇਂ ਸੱਚਮੁੱਚ ਇੱਕ ਹਨੇਰੇ, ਉਦਾਸ ਜਗ੍ਹਾ ਵਿੱਚ ਸੀ ਅਤੇ ਅਸੀਂ ਆਪਣੇ ਆਪ ਨੂੰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਉਣ ਲਈ ਕੁਝ ਬਣਾਉਣਾ ਚਾਹੁੰਦੇ ਸੀ। ਅਸੀਂ ਸ਼ਾਇਦ ਦੋ ਜਾਂ ਤਿੰਨ ਘੰਟੇ ਇਸ ਉੱਤੇ ਬਿਤਾਏ। ਇਹ 3 ਏ ਸੀ।ਐਮ. ਅਤੇ ਮੈਨੂੰ ਯਾਦ ਹੈ ਕਿ ਬਿਓਨਸੇ ਦੀ ਟੀਮ ਆਈ ਅਤੇ ਸੁਣਿਆ ਕਿ ਅਸੀਂ ਹੁਣ ਤੱਕ ਕੀ ਬਣਾਇਆ ਹੈ ਅਤੇ ਪੂਰੀ ਤਰ੍ਹਾਂ ਘਬਰਾ ਗਏ ਹਾਂ। ਇਹ ਸ਼ਾਨਦਾਰ ਸੀ।"ਰੇ ਨੇ ਅਧਿਕਾਰਤ ਚਾਰਟ ਨੂੰ ਇਹ ਵੀ ਦੱਸਿਆਃ" ਮੈਂ ਬਹੁਤ ਸਾਰੇ ਗੀਤ ਲਿਖੇ-ਮੈਂ ਇੱਕ ਸ਼ਿਫਟ ਵਿੱਚ ਪਾ ਦਿੱਤਾ। ਪਰ [ਬੇਓਨਸੇ] ਨੂੰ ਵੱਡੇ ਨਾਲ ਪਿਆਰ ਹੋ ਗਿਆ।"ਬਿਓਨਸੇ ਨੇ ਰੇਅ ਨੂੰ ਦੱਸਿਆ ਕਿ 2019 ਦੇ" "ਦਿ ਲਾਇਨ ਕਿੰਗ" "ਯੂਰਪੀਅਨ ਪ੍ਰੀਮੀਅਰ ਵਿੱਚ ਐਲਬਮ ਦਾ ਪਹਿਲਾ ਗੀਤ" "ਵੱਡਾ" "ਹੋਵੇਗਾ, ਅਤੇ ਜਿਵੇਂ ਕਿ ਵੀਡੀਓ ਵਿੱਚ ਫਡ਼ਿਆ ਗਿਆ ਹੈ, ਉਸ ਦੀ ਪ੍ਰਤੀਕਿਰਿਆ ਵਾਇਰਲ ਹੋ ਗਈ। ਰੇ ਨੇ ਟਵੀਟ ਕੀਤਾ, "ਬਿਓਨਸੇ ਨੇ ਮੈਨੂੰ ਦੱਸਿਆ ਕਿ ਮੈਂ ਨਵੀਂ ਐਲਬਮ 'ਤੇ ਟਰੈਕ 1 ਲਿਖਿਆ ਹੈ।.. ਇਸ ਨੂੰ ਵੱਡਾ ਕਿਹਾ ਜਾਂਦਾ ਹੈ। ਮੈਂ ਨਹੀਂ ਕਰ ਸਕਦਾ।"
ਰਚਨਾ ਅਤੇ ਗੀਤਾਂ ਦੀ ਵਿਆਖਿਆ।
"ਵੱਡਾ" ਤੋਂ ਪਹਿਲਾਂ "ਸੰਤੁਲਨ" ਹੈ, ਇੱਕ ਮੁਫਾਸਾ ਇੰਟਰਲੂਡ ਜਿਸ ਨੂੰ ਜੇਮਜ਼ ਅਰਲ ਜੋਨਜ਼ ਦੁਆਰਾ ਆਵਾਜ਼ ਦਿੱਤੀ ਗਈ ਹੈ, ਜੋ 2019 ਦੀ ਫਿਲਮ ਤੋਂ ਉਸ ਦੇ "ਜੀਵਨ ਦੇ ਚੱਕਰ" ਭਾਸ਼ਣ ਦਾ ਨਮੂਨਾ ਹੈ। ਦੋਵੇਂ ਟਰੈਕ ਇੱਕ ਦੂਜੇ ਵਿੱਚ ਵੱਜਦੇ ਹਨ। "ਡੈਜ਼ਡ" ਨੇ ਇਸ ਤਬਦੀਲੀ ਨੂੰ "ਟਰੈਕ ਦੇ ਬੋਲਾਂ ਨਾਲ ਚੰਗੀ ਤਰ੍ਹਾਂ ਬੰਨ੍ਹਣਾ" ਦੱਸਿਆ।"" "ਅਟਲਾਂਟਿਕ" "ਦੇ ਅਨੁਸਾਰ," "ਵੱਡੇ" "ਵਿੱਚ" "ਸ਼ਾਹੀ ਉੱਤਰਾਧਿਕਾਰੀ" "ਦਾ ਇੱਕ ਵਿਆਪਕ ਵਿਸ਼ਾ ਹੈ ਅਤੇ ਨਾਲ ਹੀ" "ਜੀਵਨ ਦੇ ਚੱਕਰ ਦੇ" "ਵਾਤਾਵਰਣ ਅਤੇ ਹੋਂਦ" "ਪਹਿਲੂਆਂ ਦੀ ਇੱਕ ਅੰਡਰਕਰੰਟ ਖੋਜ ਹੈ।"ਮੈਟਜ਼ਾਵ ਸਮੀਖਿਆ ਨੇ" "ਵੱਡੇ" "ਨੂੰ" "ਅਫ਼ਰੀਕੀ ਮਹਾਂਦੀਪ ਦੀ ਕੁਦਰਤੀ ਦੌਲਤ ਲਈ ਇੱਕ ਸਨਮਾਨ" "ਵਜੋਂ ਦਰਸਾਇਆ, ਜਦੋਂ ਕਿ ਬੇਯੋੰਸੇ ਦੇ ਬੱਚਿਆਂ ਨੂੰ ਸ਼ਰਧਾਂਜਲੀ ਵਜੋਂ ਵੀ ਕੰਮ ਕੀਤਾ, ਉਹਨਾਂ ਨੂੰ ਸਮੂਹਕ ਗਿਆਨ ਦੀ ਵਿਆਖਿਆ ਸ਼ਕਤੀ ਨੂੰ ਦਰਸਾਉਂਦਾ ਹੈ।"
ਸੰਗੀਤ ਵੀਡੀਓ.
ਇੱਕ ਸੰਗੀਤ ਵੀਡੀਓ 19 ਜੁਲਾਈ, 2019 ਨੂੰ ਜਾਰੀ ਕੀਤਾ ਗਿਆ ਸੀ, ਜੋ ਕਿ ਐਲਬਮ ਦੇ ਮੁੱਖ ਸਿੰਗਲ "ਸਪਿਰਟ" ਦੇ ਸੰਗੀਤ ਵੀਡੀਓ ਦੇ ਵਿਸਤ੍ਰਿਤ ਸੰਸਕਰਣ ਦੇ ਦੂਜੇ ਹਿੱਸੇ ਵਜੋਂ ਸੀ।
ਇੱਕ ਦੂਜਾ ਸੰਗੀਤ ਵੀਡੀਓ "ਬਲੈਕ ਇਜ਼ ਕਿੰਗ" ਵਿੱਚ ਜਾਰੀ ਕੀਤਾ ਗਿਆ ਸੀ। ਇਸ ਵਿੱਚ ਮੂਲ ਵੀਡੀਓ ਦੇ ਹਿੱਸੇ ਹਨ ਜਿਨ੍ਹਾਂ ਵਿੱਚ ਵਿਸ਼ੇਸ਼ ਤੌਰ ਉੱਤੇ ਫਿਲਮ ਲਈ ਬਣਾਈ ਗਈ ਨਵੀਂ ਫੁਟੇਜ ਹੈ।

, ਕੋਰੀਆਈ. ਸ਼ਬਦ-ਵਿਗਿਆਨ 2. ਕ੍ਰਿਆ। ਸੰਯੋਜਨ. ਨੋਟਃ ਹਾਲਾਂਕਿ ਤਜਵੀਜ਼ ਅਨੁਸਾਰ ਸੰਭਵ ਹੈ, ਫਾਰਮ ਅਭਿਆਸ ਵਿੱਚ ਘੱਟ ਹੀ ਵਰਤੇ ਜਾਂਦੇ ਹਨ। (, ਆਦਿ) ਦੇ ਰੂਪ ਵਿੱਚ ਦਿੱਤੇ ਗਏ ਸਾਰੇ ਰੂਪਾਂ ਲਈ।) ਹੇਠਾਂ, ਨੋਟ ਕਰੋ ਕਿ ਆਮ ਰੂਪ (, ਆਦਿ) ਹੈ।)। ਸ਼ਬਦ-ਵਿਗਿਆਨ 3. ਕ੍ਰਿਆ। ਸੰਯੋਜਨ. ਨੋਟਃ ਹਾਲਾਂਕਿ ਤਜਵੀਜ਼ ਅਨੁਸਾਰ ਸੰਭਵ ਹੈ, ਫਾਰਮ ਅਭਿਆਸ ਵਿੱਚ ਘੱਟ ਹੀ ਵਰਤੇ ਜਾਂਦੇ ਹਨ। (, ਆਦਿ) ਦੇ ਰੂਪ ਵਿੱਚ ਦਿੱਤੇ ਗਏ ਸਾਰੇ ਰੂਪਾਂ ਲਈ।) ਹੇਠਾਂ, ਨੋਟ ਕਰੋ ਕਿ ਆਮ ਰੂਪ (, ਆਦਿ) ਹੈ।)।,
ਹੈਰੀਏਟ ਚਿੱਟਾ ਮਛੇਰਾ

ਹੈਰੀਏਟ ਵ੍ਹਾਈਟ ਫਿਸ਼ਰ ਐਂਡਰਿਊ (1861-1939) ਇੱਕ ਅਮਰੀਕੀ ਸੀ ਜੋ ਇੱਕ ਲੋਕੋਮੋਬਾਈਲ ਵਿੱਚ ਦੁਨੀਆ ਦਾ ਚੱਕਰ ਲਗਾਉਣ ਵਾਲੀ ਪਹਿਲੀ ਔਰਤ ਵਜੋਂ ਜਾਣੀ ਜਾਂਦੀ ਸੀ।
ਜਨਮ ਅਤੇ ਮੁਢਲਾ ਜੀਵਨ।
ਹੈਰੀਏਟ ਵ੍ਹਾਈਟ ਦਾ ਜਨਮ 31 ਮਾਰਚ 1861 ਨੂੰ ਕ੍ਰੌਫੋਰਡ ਕਾਊਂਟੀ, ਪੈਨਸਿਲਵੇਨੀਆ ਵਿੱਚ ਹੋਇਆ ਸੀ. ਉਹ ਆਸਕਰ ਏ ਦੀ ਧੀ ਸੀ। ਚਿੱਟੇ ਅਤੇ ਹੈਨਾ ਮਛੇਰੇ, ਅਤੇ ਕਲੀਵਲੈਂਡ ਓਹੀਓ ਵਿੱਚ ਨੌਜਵਾਨ ਔਰਤਾਂ ਦੇ ਕਲਾਸੀਕਲ ਮਦਰੱਸੇ ਵਿੱਚ ਸਿੱਖਿਆ ਪ੍ਰਾਪਤ ਕੀਤੀ ਸੀ। ਜੌਹਨਸਟਾਊਨ ਹਡ਼੍ਹ ਦੇ ਸਮੇਂ ਉਸਨੇ ਪੀਡ਼ਤਾਂ ਦੀ ਦੇਖਭਾਲ ਕੀਤੀ। ਵੂ ਟਿੰਗਫਾਂਗ, ਚੀਨੀ ਡਿਪਲੋਮੈਟ ਅਤੇ ਸਿਆਸਤਦਾਨ, ਸ਼੍ਰੀਮਤੀ ਨੂੰ ਸੱਦਿਆ ਜਾਂਦਾ ਹੈ। ਹੈਰੀਏਟ ਵ੍ਹਾਈਟ ਫਿਸ਼ਰ "ਅਮਰੀਕਾ ਦੀ ਸਭ ਤੋਂ ਸ਼ਾਨਦਾਰ ਔਰਤ।"
ਰੇਲ ਹਾਦਸਾ।
8 ਅਕਤੂਬਰ, 1902 ਨੂੰ, ਦੋ ਪੈਨਸਿਲਵੇਨੀਆ ਰੇਲਮਾਰਗ ਯਾਤਰੀ ਰੇਲ ਗੱਡੀਆਂ ਮੇਨਲੋ ਪਾਰਕ, ਨਿਊ ਜਰਸੀ ਵਿੱਚ ਟਕਰਾ ਗਈਆਂ। ਹੈਰੀਏਟ ਮਛੇਰੇ ਗੰਭੀਰ ਰੂਪ ਵਿੱਚ ਜ਼ਖਮੀ ਹੋ ਗਏ। ਉਸ ਦੀਆਂ ਸੱਟਾਂ ਦੀ ਇੱਕ ਰਿਪੋਰਟ ਵਿੱਚ ਕਿਹਾ ਗਿਆ ਹੈ ਕਿ ਉਹ ਅੱਠ ਹਫ਼ਤਿਆਂ ਤੋਂ ਪ੍ਰੈਸਬਾਇਟੇਰੀਅਨ ਹਸਪਤਾਲ (ਨਿਊਯਾਰਕ ਸ਼ਹਿਰ) ਵਿੱਚ ਸੀ, ਟੁੱਟੀਆਂ ਕੁੱਲ੍ਹੇ, ਰੀਡ਼੍ਹ ਦੀ ਹੱਡੀ ਦੀ ਸੱਟ ਅਤੇ ਅੰਦਰੂਨੀ ਸੱਟ ਨਾਲ ਹਸਪਤਾਲ ਵਿੱਚ ਦਾਖਲ ਸੀ।
ਸਟੀਲ ਉਦਯੋਗ.
ਆਪਣੇ ਪਤੀ ਦੀ ਮੌਤ ਤੋਂ ਬਾਅਦ, ਹੈਰਿਏਟ ਫਿਸ਼ਰ ਨੇ ਟ੍ਰੈਂਟਨ, ਨਿਊ ਜਰਸੀ ਵਿੱਚ ਈਗਲ ਸਟੀਲ ਦੇ ਕੰਮਾਂ (ਬਾਅਦ ਵਿੱਚ ਫਿਸ਼ਰ ਅਤੇ ਨੌਰਿਸ ਐਨਵਿਲ ਵਰਕਸ ਦਾ ਨਾਮ ਦਿੱਤਾ ਗਿਆ) ਦਾ ਪ੍ਰਬੰਧਨ ਸੰਭਾਲ ਲਿਆ। ਉਹ ਨਿਰਮਾਤਾਵਾਂ ਦੀ ਰਾਸ਼ਟਰੀ ਐਸੋਸੀਏਸ਼ਨ ਦੀ ਇਕਲੌਤੀ ਮਹਿਲਾ ਮੈਂਬਰ ਸੀ। ਉਸ ਨੂੰ 1911 ਵਿੱਚ "ਵਾਸ਼ਿੰਗਟਨ ਪੋਸਟ" ਵਿੱਚ ਹਵਾਲਾ ਦਿੱਤਾ ਗਿਆ ਹੈ, ਜਿਸ ਵਿੱਚ ਉਸ ਨੇ ਕਾਰੋਬਾਰ ਵਿੱਚ ਆਪਣੀ ਸ਼ਮੂਲੀਅਤ ਦਾ ਵਰਣਨ ਕੀਤਾ ਹੈਃ
"ਸ਼੍ਰੀਮਤੀ ਨੇ ਕਿਹਾ, "ਹਾਲਾਂਕਿ ਮੈਨੂੰ ਬਚਪਨ ਵਿੱਚ ਵੀ ਮਸ਼ੀਨਰੀ ਪਸੰਦ ਸੀ। ਮਛੇਰੇ, "ਇਹ ਮੇਰੇ ਪਤੀ ਦੀ ਬਿਮਾਰੀ ਸੀ ਅਤੇ ਹਰ ਔਰਤ ਦੀ ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਮਦਦ ਕਰਨ ਦੀ ਇੱਛਾ ਸੀ ਜਿਸ ਨੇ ਮੈਨੂੰ ਬਾਜ਼ ਦੇ ਕੰਮ ਵਿੱਚ ਦਾਖਲ ਹੋਣ ਲਈ ਪ੍ਰੇਰਿਤ ਕੀਤਾ, ਜਿਸ ਵਿੱਚੋਂ ਸ਼੍ਰੀਮਾਨ। ਮਛੇਰੇ ਸਿਰ ਸਨ। ਮੈਂ 'ਬੌਸ' ਵਜੋਂ ਅੰਦਰ ਗਿਆ ਪਰ ਮੈਨੂੰ ਜਲਦੀ ਹੀ ਪਤਾ ਲੱਗ ਗਿਆ ਕਿ ਜੇ ਮੇਰੇ ਕਰਮਚਾਰੀਆਂ ਦੁਆਰਾ ਮੇਰਾ ਸਨਮਾਨ ਕੀਤਾ ਜਾਣਾ ਹੈ, ਤਾਂ ਮੈਨੂੰ ਉਨ੍ਹਾਂ ਨਾਲੋਂ ਜ਼ਿਆਦਾ ਜਾਣਨਾ ਪਵੇਗਾ। ਇਸ ਲਈ, ਮੈਂ ਇੱਕ ਨਿਯਮਤ ਸਿੱਖਿਆਰਥੀ ਵਜੋਂ ਸ਼ੁਰੂਆਤ ਕੀਤੀ, ਸਟੀਲ ਨੂੰ ਸ਼ਾਂਤ ਕਰਨਾ, ਇੱਕ ਐਨਵਿਲ ਦੇ ਚਿਹਰੇ ਨੂੰ ਛਾਣਨਾ, ਅੱਖਾਂ ਨੂੰ ਢਾਲਣਾ ਅਤੇ ਰੇਲ ਬਣਾਉਣਾ ਸਿੱਖਿਆ। ਅਸਲ ਵਿੱਚ, ਮੈਂ ਕਾਰੋਬਾਰ ਦੇ ਹਰ ਵਿਭਾਗ ਵਿੱਚ ਸੂਰ-ਲੋਹੇ ਨੂੰ ਪਿਘਲਣ ਤੋਂ ਲੈ ਕੇ ਠੇਕੇ ਲਈ ਬੋਲੀ ਲਗਾਉਣ ਤੱਕ ਇੱਕ ਪੂਰਾ ਕੋਰਸ ਕੀਤਾ। ਇਸ ਤੋਂ ਪਹਿਲਾਂ ਕਿ ਮੈਂ ਕੰਮ ਪੂਰਾ ਕਰ ਲਿਆ, ਮੈਂ ਲੋਹੇ ਅਤੇ ਸਟੀਲ, ਮਸ਼ੀਨਰੀ ਦੀ ਧੁੰਦ ਅਤੇ ਜਾਲੀ ਦੀ ਆਵਾਜ਼ ਨਾਲ ਕੰਮ ਕਰਨਾ ਸੱਚਮੁੱਚ ਸਿੱਖ ਲਿਆ।"
ਉਸ ਦੀ ਦੌਲਤ 1906 ਵਿੱਚ $2,000,000 ਦੱਸੀ ਗਈ ਸੀ। "ਉਸ ਨੇ ਪਨਾਮਾ ਨਹਿਰ ਦੇ ਉਪਕਰਣਾਂ ਦੇ ਹਿੱਸੇ ਵਜੋਂ ਆਪਣੇ ਵਿਰੋਧੀਆਂ ਨੂੰ ਘੱਟ ਬੋਲੀ ਲਗਾਈ ਅਤੇ ਆਪਣੀ ਯੋਜਨਾ ਦੇ ਆਉਟਪੁੱਟ ਦੀ ਉਸ ਵਿਸ਼ੇਸ਼ਤਾ ਉੱਤੇ $1,000,000 ਦੀ ਕਮਾਈ ਕੀਤੀ।"
ਦੁਨੀਆ ਭਰ ਵਿੱਚ ਗੱਡੀ ਚਲਾਉਣ ਵਾਲੀ ਪਹਿਲੀ ਔਰਤ
ਉਸ ਦੀ ਯਾਤਰਾ ਤੋਂ ਪਹਿਲਾਂ ਦੀਆਂ ਸ਼ੁਰੂਆਤੀ ਰਿਪੋਰਟਾਂ ਤੋਂ ਪਤਾ ਲੱਗਿਆ ਕਿ ਉਸ ਦੀ ਚਾਰ ਸੀਟਾਂ ਵਾਲੀ ਕਾਰ ਬ੍ਰਿਜਪੋਰਟ, ਕਨੈਕਟੀਕਟ ਵਿੱਚ ਬਣਾਈ ਗਈ ਸੀ ਅਤੇ ਇਸ ਵਿੱਚ 40-ਹਾਰਸ ਪਾਵਰ ਦਾ ਇੰਜਣ ਸੀ ਜਿਸ ਵਿੱਚ ਕੋਈ ਵਿਸ਼ੇਸ਼ ਉਪਕਰਣ ਨਹੀਂ ਸੀ। ਉਸ ਦੇ ਯੋਜਨਾਬੱਧ ਸਾਥੀ ਹਾਰੋਲਡ ਮਛੇਰੇ ਦੇ ਝਰਨੇ (ਇੱਕ ਰਿਸ਼ਤੇਦਾਰ), ਐਲਬਰਟ ਨਾਮ ਦਾ ਇੱਕ ਸ਼ੈੱਫ ਅਤੇ ਇੱਕ ਨੌਕਰਾਣੀ ਸਨ। ਉਸ ਨੇ ਇੱਕ ਪਾਲਤੂ ਬਾਂਦਰ, ਇੱਕ ਬਲਦ ਟੈਰੀਅਰ ਅਤੇ ਇੱਕ ਪਗ ਨਾਲ ਵੀ ਯਾਤਰਾ ਕੀਤੀ। ਯੋਜਨਾਬੱਧ ਮਾਰਗ ਕਾਰ ਨੂੰ ਇੰਗਲੈਂਡ ਭੇਜਣਾ, ਲੇਕ ਕੋਮੋ ਵਿਖੇ ਉਸ ਦੇ ਇਟਾਲੀਅਨ ਵਿਲਾ ਦੀ ਯਾਤਰਾ ਕਰਨਾ, ਅਤੇ ਫਿਰ ਮਿਸਰ, ਭਾਰਤ, ਜਪਾਨ ਤੋਂ ਹੁੰਦੇ ਹੋਏ ਜਾਰੀ ਰੱਖਣਾ ਅਤੇ ਸੰਯੁਕਤ ਰਾਜ ਅਮਰੀਕਾ ਵਾਪਸ ਜਾਣਾ ਸੀ, ਜੁਲਾਈ 1909 ਵਿੱਚ ਅਮਰੀਕਾ ਦੇ ਆਟੋਮੋਬਾਈਲ ਕਲੱਬ ਵਿੱਚ ਇੱਕ ਵਧੀਆ ਸਮੁੰਦਰੀ ਯਾਤਰਾ ਪਾਰਟੀ ਦਾ ਐਲਾਨ ਕੀਤਾ ਗਿਆ ਸੀ। ਯਾਤਰੀ 19 ਜੁਲਾਈ, 1909 ਨੂੰ ਰਵਾਨਾ ਹੋਏ. ਇਹ ਦੱਸਿਆ ਗਿਆ ਸੀ ਕਿ ਉਹ ਨਵੰਬਰ 1909 ਤੱਕ ਲੇਕ ਕੋਮੋ ਪਹੁੰਚੀ ਸੀ. ਇੱਕ ਸਮਕਾਲੀ ਅਖ਼ਬਾਰ ਦੇ ਖਾਤੇ ਵਿੱਚ ਕਿਹਾ ਗਿਆ ਸੀ ਕਿ ਮਛੇਰੇ ਅਤੇ ਉਨ੍ਹਾਂ ਦੇ ਦਲ ਨੇ ਜਪਾਨ ਦੀ ਆਪਣੀ ਯਾਤਰਾ ਪੂਰੀ ਕਰ ਲਈ ਸੀ ਅਤੇ ਯਾਤਰੀ ਅਤੇ ਵਾਹਨ ਸੈਨ ਫਰਾਂਸਿਸਕੋ, ਕੈਲੀਫੋਰਨੀਆ ਵਾਪਸ ਆ ਗਏ ਸਨ। ਉਹ 16 ਅਗਸਤ, 1910 ਨੂੰ ਦੁਨੀਆ ਭਰ ਵਿੱਚ ਆਪਣੀ ਯਾਤਰਾ ਪੂਰੀ ਕਰਦੇ ਹੋਏ ਟੈਰੀਟਾਊਨ, ਨਿਊਯਾਰਕ ਪਹੁੰਚੀ। ਫਿਸ਼ਰ ਨੇ ਆਪਣੇ ਸਾਹਸ ਬਾਰੇ ਇੱਕ ਕਿਤਾਬ ਲਿਖੀ ਜਿਸ ਦਾ ਸਿਰਲੇਖ ਸੀ "ਇੱਕ ਮੋਟਰ ਵਿੱਚ ਇੱਕ ਔਰਤ ਦਾ ਵਿਸ਼ਵ ਦੌਰਾ"।
ਨਿੱਜੀ ਜੀਵਨ.
ਉਸ ਦਾ ਪਹਿਲਾ ਜਾਣਿਆ ਵਿਆਹ ਕਲਾਰਕ ਫਿਸ਼ਰ ਨਾਲ ਸੀ। ਉਨ੍ਹਾਂ ਦਾ ਵਿਆਹ 20 ਜੁਲਾਈ, 1898 ਨੂੰ ਲੰਡਨ, ਇੰਗਲੈਂਡ ਵਿੱਚ ਹੋਇਆ ਸੀ. "ਟ੍ਰੈਂਟਨ ਸ਼ਾਮ ਦੇ ਸਮੇਂ" ਵਿੱਚ ਉਨ੍ਹਾਂ ਦੇ ਵਿਆਹ ਦੀ ਰਿਪੋਰਟ ਵਿੱਚ ਲਾਡ਼ੀ ਦਾ ਨਾਮ ਸ਼੍ਰੀਮਤੀ ਦੱਸਿਆ ਗਿਆ ਹੈ। ਵ੍ਹਾਈਟ, ਇੱਕ ਵਿਧਵਾ ਜੋ 1896 ਵਿੱਚ ਫਲੱਸ਼ਿੰਗ ਵਿੱਚ ਚਲੀ ਗਈ, ਰਾਣੀਆਂ. ਹਾਲਾਂਕਿ, ਹੈਰੀਏਟ ਫਿਸ਼ਰ ਦੀ ਬਾਅਦ ਵਿੱਚ ਇੱਕ ਇੰਟਰਵਿਊ ਵਿੱਚ ਕਿਹਾ ਗਿਆ ਕਿ ਉਹ ਜਨਮ ਤੋਂ ਇੱਕ "ਚਿੱਟੀ" ਸੀ ਅਤੇ ਉਸ ਦੀ ਮਾਂ ਆਪਣੇ ਪਤੀ ਨਾਲ ਦੂਰ ਦੀ ਸਬੰਧ ਰੱਖਦੀ ਸੀ। ਮੱਛੀ ਫਡ਼ਨ ਵਾਲੇ ਦੀ ਮੌਤ 1903 ਵਿੱਚ ਹੋਈ। ਉਸ ਨੇ 27 ਅਪ੍ਰੈਲ, 1912 ਨੂੰ ਮੈਨਹੱਟਨ ਵਿੱਚ ਆਰਜੈਂਟੀਨ ਜਲ ਸੈਨਾ ਦੇ ਇੱਕ ਅਧਿਕਾਰੀ ਸਿਲਵਾਨੋ ਅਲਫਰੇਡੋ ਐਂਡਰੂ ਨਾਲ ਦੁਬਾਰਾ ਵਿਆਹ ਕਰਵਾ ਲਿਆ। ਪ੍ਰੈੱਸ ਵਿੱਚ ਇਸ ਨੂੰ ਇੱਕ ਸ਼ਾਂਤ ਸਮਾਰੋਹ ਵਜੋਂ ਦਰਸਾਇਆ ਗਿਆ ਸੀ ਕਿਉਂਕਿ ਲਾਡ਼ੇ ਦੇ ਭਰਾ (ਐੱਡਗਾਰਡ) ਦੀ ਕੁਝ ਦਿਨ ਪਹਿਲਾਂ "ਟਾਇਟੈਨਿਕ" ਉੱਤੇ ਮੌਤ ਹੋ ਗਈ ਸੀ।
ਫਿਸ਼ਰ ਇੱਕ ਵਿਰੋਧੀ-ਸਫਰੇਜ਼ਿਸਟ ਸੀ ਅਤੇ 1913 ਵਿੱਚ ਨਿਊ ਜਰਸੀ ਵਿੱਚ ਔਰਤਾਂ ਦੇ ਵੋਟ ਅਧਿਕਾਰ ਦੇ ਵਿਰੁੱਧ ਗਵਾਹੀ ਦਿੱਤੀ।

,
ਆਈਰਿਸ (ਮਿਥਿਹਾਸ)

ਪ੍ਰਾਚੀਨ ਯੂਨਾਨੀ ਧਰਮ ਅਤੇ ਮਿਥਿਹਾਸ ਵਿੱਚ, ਆਈਰਿਸ (;;) ਦੇਵਤਾ ਥੌਮਾਸ ਅਤੇ ਇਲੈਕਟ੍ਰਾ ਦੀ ਇੱਕ ਧੀ ਹੈ, ਸਤਰੰਗੀ ਧਨੁਸ਼ ਅਤੇ ਦੇਵਤਿਆਂ ਦੇ ਸੰਦੇਸ਼ਵਾਹਕ ਦੀ ਮੂਰਤੀ, ਓਲੰਪਿਕ ਅਤੇ ਵਿਸ਼ੇਸ਼ ਤੌਰ 'ਤੇ ਰਾਣੀ ਹੇਰਾ ਦੀ ਸੇਵਕ ਹੈ। ਆਈਰਿਸ ਕਈ ਕਹਾਣੀਆਂ ਵਿੱਚ ਦਿਖਾਈ ਦਿੰਦੀ ਹੈ ਜਿਸ ਵਿੱਚ ਦੇਵਤਿਆਂ ਤੋਂ ਅਤੇ ਉਹਨਾਂ ਨੂੰ ਸੰਦੇਸ਼ ਦਿੱਤੇ ਜਾਂਦੇ ਹਨ ਜਾਂ ਕੰਮ ਚੱਲ ਰਹੇ ਹਨ ਪਰ ਉਸ ਦੀ ਆਪਣੀ ਕੋਈ ਵਿਲੱਖਣ ਮਿਥਿਹਾਸਕ ਕਥਾ ਨਹੀਂ ਹੈ। ਇਸੇ ਤਰ੍ਹਾਂ, ਇੱਕ ਇਤਿਹਾਸਕ ਪੰਥ ਅਤੇ ਆਈਰਿਸ ਦੀ ਪੂਜਾ ਦੀ ਬਹੁਤ ਘੱਟ ਜਾਂ ਕੋਈ ਵੀ ਸਬੂਤ ਬਚੇ ਹੋਏ ਰਿਕਾਰਡਾਂ ਵਿੱਚ ਪ੍ਰਮਾਣਿਤ ਨਹੀਂ ਹੈ, ਜਿਸ ਵਿੱਚ ਡੇਲੋਸ ਟਾਪੂ ਤੋਂ ਸਿਰਫ ਕੁਝ ਨਿਸ਼ਾਨ ਬਚੇ ਹਨ। ਪ੍ਰਾਚੀਨ ਕਲਾ ਵਿੱਚ, ਆਈਰਿਸ ਨੂੰ ਇੱਕ ਖੰਭਾਂ ਵਾਲੀ ਨੌਜਵਾਨ ਔਰਤ ਦੇ ਰੂਪ ਵਿੱਚ ਦਰਸਾਇਆ ਗਿਆ ਹੈ ਜੋ ਇੱਕ ਕੈਡੂਸੀਅਸ, ਸੰਦੇਸ਼ਵਾਹਕਾਂ ਦਾ ਪ੍ਰਤੀਕ ਅਤੇ ਦੇਵਤਿਆਂ ਲਈ ਪਾਣੀ ਦਾ ਘਡ਼ਾ ਚੁੱਕਦੀ ਹੈ। ਆਈਰਿਸ ਨੂੰ ਰਵਾਇਤੀ ਤੌਰ ਉੱਤੇ ਪੱਛਮੀ ਹਵਾ ਦੇ ਦੇਵਤਾ ਅਤੇ ਚਾਰ ਅਨੀਮੋਈ ਵਿੱਚੋਂ ਇੱਕ, ਜ਼ੇਫਿਰਸ ਦੀ ਪਤਨੀ ਵਜੋਂ ਦੇਖਿਆ ਜਾਂਦਾ ਸੀ, ਜਿਸ ਦੁਆਰਾ ਉਹ ਕੁੱਝ ਸੰਸਕਰਣਾਂ ਵਿੱਚ ਪੋਥੋਸ ਦੀ ਮਾਂ ਹੈ।
ਸ਼ਬਦਾਵਲੀ.
ਪ੍ਰਾਚੀਨ ਯੂਨਾਨੀ ਨਾਮ ਦਾ ਅਰਥ ਹੈ ਚੰਦਰਮਾ ਦਾ ਸਤਰੰਗੀ ਅਤੇ ਪ੍ਰਭਾਸ਼ਿਤ ਦੋਵੇਂ। ਕੋਰਿਨਥ ਦਾ ਇੱਕ ਸ਼ਿਲਾਲੇਖ ਇੱਕ ਮੂਲ ਰੂਪ ("ਵਾਇਰਸ") ਦਾ ਸਬੂਤ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ ਜਿਸ ਵਿੱਚ ਇੱਕ ਡਿਗਾਮਮਾ ਸੀ ਜਿਸ ਨੂੰ ਆਖਰਕਾਰ ਸੁੱਟ ਦਿੱਤਾ ਗਿਆ ਸੀ। ਇਹ ਨਾਮ ਪੂਰਵ-ਯੂਨਾਨੀ ਮੂਲ ਦਾ ਜਾਪਦਾ ਹੈ। ਇੱਕ ਪ੍ਰੋਟੋ-ਇੰਡੋ-ਯੂਰਪੀਅਨ ਪ੍ਰੀ-ਫਾਰਮ "* ਉਹ2ਆਈ-ਆਰ-ਆਈ-" ਦਾ ਸੁਝਾਅ ਦਿੱਤਾ ਗਿਆ ਹੈ, ਹਾਲਾਂਕਿ ਮਧੂ ਮੱਖੀਆਂ ਨੂੰ ਪ੍ਰੇਰਿਤ ਕਰਨਾ ਮੁਸ਼ਕਲ ਲੱਗਦਾ ਹੈ।'
ਪਰਿਵਾਰ।
ਹੇਸਿਓਡ ਦੇ "ਥੀਓਗਨੀ" ਦੇ ਅਨੁਸਾਰ, ਆਈਰਿਸ ਥੌਮਸ ਅਤੇ ਓਸ਼ੀਅਨਡ ਇਲੈਕਟ੍ਰਾ ਦੀ ਧੀ ਹੈ ਅਤੇ ਹਾਰਪੀਜ਼ ਦੀ ਭੈਣ ਹੈਃ ਆਰਕ ਅਤੇ ਓਸਿਪੀਟ। ਟਾਈਟਨੋਮਾਕੀ ਦੌਰਾਨ, ਆਈਰਿਸ ਓਲੰਪਿਕ ਦੇਵਤਿਆਂ ਦਾ ਸੰਦੇਸ਼ਵਾਹਕ ਸੀ ਜਦੋਂ ਕਿ ਉਸ ਦੀ ਭੈਣ ਸੰਦੂਕ ਨੇ ਓਲੰਪਿਕ ਖਿਡਾਰੀਆਂ ਨੂੰ ਧੋਖਾ ਦਿੱਤਾ ਅਤੇ ਦੇਵਤਾ ਦੇ ਦੁਸ਼ਮਣ, ਟਾਈਟਨਜ਼ ਦਾ ਸੰਦੇਸ਼ਵਾਹਕ ਬਣ ਗਈ।
ਉਹ ਸਤਰੰਗੀ ਦੀ ਦੇਵੀ ਹੈ। ਉਹ ਦੇਵੀ-ਦੇਵਤਿਆਂ ਨੂੰ ਅੰਤਰ ਪੀਣ ਲਈ ਵੀ ਪਰੋਸਦੀ ਹੈ।
ਜ਼ੇਫਿਰਸ, ਜੋ ਪੱਛਮੀ ਹਵਾ ਦਾ ਦੇਵਤਾ ਹੈ, ਉਸ ਦੀ ਪਤਨੀ ਹੈ। ਛੇਵੀਂ ਸਦੀ ਬੀ. ਸੀ. ਦੇ ਯੂਨਾਨੀ ਗੀਤਕਾਰ ਕਵੀ ਐਲਕੇਅਸ ਦੇ ਅਨੁਸਾਰ, ਉਹਨਾਂ ਦਾ ਇੱਕ ਪੁੱਤਰ ਸੀ ਜਿਸ ਦਾ ਨਾਮ ਪੋਥੋਸ ਸੀ, ਜਾਂ ਬਦਲ ਵਜੋਂ ਉਹ ਪਿਆਰ ਦੇ ਦੇਵਤਾ, ਇਰੋਸ ਦੇ ਮਾਪੇ ਸਨ, ਹਾਲਾਂਕਿ ਇਰੋਸ ਨੂੰ ਆਮ ਤੌਰ 'ਤੇ ਏਰੇਸ ਅਤੇ ਐਫਰੋਡਾਈਟ ਦਾ ਪੁੱਤਰ ਕਿਹਾ ਜਾਂਦਾ ਹੈ। ਨਾਨਨਸ ਦੇ "ਡਾਇਓਨੀਸਿਆਕਾ" ਦੇ ਅਨੁਸਾਰ, ਆਈਰਿਸ ਦਾ ਭਰਾ ਹਾਈਡਾਸਪੇਸ ਹੈ।
ਉਸ ਨੂੰ ਸਮੁੰਦਰ ਅਤੇ ਅਸਮਾਨ ਦੀਆਂ ਦੇਵੀਆਂ ਵਿੱਚੋਂ ਇੱਕ ਵਜੋਂ ਵੀ ਜਾਣਿਆ ਜਾਂਦਾ ਹੈ। ਆਈਰਿਸ ਦੇਵਤਿਆਂ ਨੂੰ ਮਨੁੱਖਤਾ ਨਾਲ ਜੋਡ਼ਦਾ ਹੈ। ਉਹ ਦੁਨੀਆ ਦੇ ਇੱਕ ਸਿਰੇ ਤੋਂ ਦੂਜੇ ਸਿਰੇ ਤੱਕ ਅਤੇ ਸਮੁੰਦਰ ਅਤੇ ਅੰਡਰਵਰਲਡ ਦੀ ਡੂੰਘਾਈ ਵਿੱਚ ਹਵਾ ਦੀ ਗਤੀ ਨਾਲ ਯਾਤਰਾ ਕਰਦੀ ਹੈ।
ਮਿਥਿਹਾਸ.
ਟਾਈਟਨੋਮਾਕੀ.
ਕਿਹਾ ਜਾਂਦਾ ਹੈ ਕਿ ਆਈਰਿਸ ਰੱਬ ਦੇ ਸੰਦੇਸ਼ਾਂ ਨੂੰ ਮਨੁੱਖਾਂ ਤੱਕ ਪਹੁੰਚਾਉਂਦੇ ਹੋਏ ਸਤਰੰਗੀ ਧਨੁਸ਼ ਉੱਤੇ ਯਾਤਰਾ ਕਰਦਾ ਹੈ। ਕੁੱਝ ਰਿਕਾਰਡ ਵਿੱਚ, ਆਈਰਿਸ ਸਾਥੀ ਸੰਦੇਸ਼ਵਾਹਕ ਦੇਵੀ ਆਰਕ ("ਸਵਿਫਟ", "ਤੇਜ਼") ਦੀ ਭੈਣ ਹੈ, ਜੋ ਓਲੰਪਿਕ ਦੇਵਤਿਆਂ ਦੀ ਸੰਗਤ ਤੋਂ ਬਾਹਰ ਨਿਕਲ ਕੇ ਟਾਇਟਨੋਮਾਕੀ ਦੌਰਾਨ ਆਪਣੀ ਸੰਦੇਸ਼ਵਾਹਕ ਦੇਵੀ ਵਜੋਂ ਟਾਇਟਨਜ਼ ਨਾਲ ਸ਼ਾਮਲ ਹੋ ਗਈ, ਜਿਸ ਨਾਲ ਦੋਵੇਂ ਭੈਣਾਂ ਸੰਦੇਸ਼ਵਾਹਕ ਦੇਵੀਆਂ ਦੇ ਦੁਸ਼ਮਣ ਬਣ ਗਈਆਂ। ਜਿਉਸ ਅਤੇ ਉਸ ਦੇ ਸਹਿਯੋਗੀਆਂ ਦੁਆਰਾ ਯੁੱਧ ਜਿੱਤਣ ਤੋਂ ਬਾਅਦ, ਜ਼ਿਊਸ ਨੇ ਉਸ ਤੋਂ ਆਰਕ ਦੇ ਖੰਭ ਪਾਡ਼ ਦਿੱਤੇ ਅਤੇ ਸਮੇਂ ਦੇ ਨਾਲ ਉਨ੍ਹਾਂ ਨੂੰ ਨੀਲੇਡ ਥੀਟਿਸ ਨੂੰ ਉਸ ਦੇ ਵਿਆਹ ਵਿੱਚ ਤੋਹਫ਼ੇ ਵਜੋਂ ਦਿੱਤਾ, ਜਿਸ ਨੇ ਬਦਲੇ ਵਿੱਚ ਉਨ੍ਹਾਂ ਨੂੰ ਆਪਣੇ ਪੁੱਤਰ, ਆਕਿਲਸ ਨੂੰ ਦੇ ਦਿੱਤਾ, ਜਿਸ ਨੇ ਉਨ੍ਹਾਂ ਨੂੰ ਆਪਣੇ ਪੈਰਾਂ ਉੱਤੇ ਪਹਿਨਿਆ ਹੋਇਆ ਸੀ। ਅਕਿਲਸ ਨੂੰ ਕਈ ਵਾਰ "ਪੋਡਾਰਕਸ" ([ਕਿਸ਼ਤੀ ਦੇ ਖੰਭਾਂ ਵਰਗੇ ਪੈਰ) ਵਜੋਂ ਜਾਣਿਆ ਜਾਂਦਾ ਸੀ। ਪੋਡਾਰਸ ਟ੍ਰੋਏ ਦੇ ਰਾਜੇ, ਪ੍ਰਿਯਮ ਦਾ ਅਸਲ ਨਾਮ ਵੀ ਸੀ।
ਦੇਵਤਿਆਂ ਦਾ ਸੰਦੇਸ਼ਵਾਹਕ।
ਹੈਡਸ ਦੁਆਰਾ ਆਪਣੀ ਧੀ ਪਰਸੀਫੋਨ ਦੇ ਅਗਵਾ ਹੋਣ ਤੋਂ ਬਾਅਦ, ਖੇਤੀਬਾਡ਼ੀ ਦੀ ਦੇਵੀ ਨੇ ਐਲੂਸਿਸ ਵਿੱਚ ਆਪਣੇ ਮੰਦਰ ਵਿੱਚ ਵਾਪਸ ਆ ਕੇ ਧਰਤੀ ਨੂੰ ਬੰਜਰ ਬਣਾ ਦਿੱਤਾ, ਜਿਸ ਨਾਲ ਇੱਕ ਵੱਡਾ ਕਾਲ ਪਿਆ ਜਿਸ ਨੇ ਮਨੁੱਖਾਂ ਨੂੰ ਮਾਰ ਦਿੱਤਾ, ਅਤੇ ਨਤੀਜੇ ਵਜੋਂ ਦੇਵਤਿਆਂ ਨੂੰ ਬਲੀਦਾਨ ਦੇਣਾ ਬੰਦ ਹੋ ਗਿਆ। ਜ਼ੀਅਸ ਨੇ ਫਿਰ ਆਈਰਿਸ ਨੂੰ ਡਿਮੀਟਰ ਕਰਨ ਲਈ ਭੇਜਿਆ, ਉਸ ਨੂੰ ਦੂਜੇ ਦੇਵਤਿਆਂ ਨਾਲ ਸ਼ਾਮਲ ਹੋਣ ਅਤੇ ਉਸ ਦਾ ਸਰਾਪ ਚੁੱਕਣ ਲਈ ਬੁਲਾਇਆ; ਪਰ ਕਿਉਂਕਿ ਉਸ ਦੀ ਧੀ ਵਾਪਸ ਨਹੀਂ ਆਈ, ਡੀਮੀਟਰ ਨੂੰ ਯਕੀਨ ਨਹੀਂ ਹੋਇਆ।
ਇੱਕ ਬਿਰਤਾਂਤ ਵਿੱਚ, ਜਦੋਂ ਲੇਟੋ ਅਤੇ ਉਸ ਦੇ ਬੱਚਿਆਂ ਨੇ ਜ਼ੀਅਸ ਨੂੰ ਪ੍ਰੋਮੀਥੀਅਸ ਨੂੰ ਉਸ ਦੀ ਤਸੀਹੇ ਤੋਂ ਰਿਹਾਅ ਕਰਨ ਦੀ ਬੇਨਤੀ ਕੀਤੀ, ਤਾਂ ਜ਼ੀਅਸ ਨੇ ਮੰਨਿਆ, ਅਤੇ ਮੰਦਭਾਗੇ ਪ੍ਰੋਮੀਥੀਅਸ ਨੂੰ ਆਜ਼ਾਦ ਕਰਨ ਲਈ ਹੈਰੈਕਲਾਂ ਦਾ ਆਦੇਸ਼ ਦੇਣ ਲਈ ਆਈਰਿਸ ਭੇਜਿਆ।
ਸੀਕਸ ਦੇ ਜਹਾਜ਼ ਦੇ ਟੁੱਟਣ ਵਿੱਚ ਡੁੱਬਣ ਤੋਂ ਬਾਅਦ, ਹੇਰਾ ਨੇ ਆਈਰਿਸ ਨੂੰ ਨੀਂਦ ਦੇ ਦੇਵਤਾ, ਸੰਮੋਹਨ ਨੂੰ ਆਪਣੇ ਆਦੇਸ਼ ਦਿੱਤੇ। ਆਈਰਿਸ ਨੇ ਉੱਡ ਕੇ ਉਸ ਨੂੰ ਆਪਣੀ ਗੁਫਾ ਵਿੱਚ ਪਾਇਆ, ਅਤੇ ਉਸ ਨੂੰ ਦੱਸਿਆ ਕਿ ਹੇਰਾ ਚਾਹੁੰਦੀ ਹੈ ਕਿ ਸੀਕਸ ਦੀ ਪਤਨੀ, ਐਲਸੀਓਨ, ਨੂੰ ਉਸ ਦੇ ਸੁਪਨਿਆਂ ਵਿੱਚ ਉਸ ਦੇ ਅਜ਼ੀਜ਼ ਦੀ ਮੌਤ ਬਾਰੇ ਸੂਚਿਤ ਕੀਤਾ ਜਾਵੇ। ਹੇਰਾ ਦੀ ਕਮਾਂਡ ਦੇਣ ਤੋਂ ਬਾਅਦ, ਆਈਰਿਸ ਤੁਰੰਤ ਚਲੀ ਗਈ, ਬਹੁਤ ਲੰਬੇ ਸਮੇਂ ਤੱਕ ਸੰਮੋਹਨ ਦੇ ਨੇਡ਼ੇ ਨਹੀਂ ਖਡ਼੍ਹੀ, ਕਿਉਂਕਿ ਉਸ ਦੀਆਂ ਸ਼ਕਤੀਆਂ ਨੇ ਉਸ ਨੂੰ ਫਡ਼ ਲਿਆ, ਅਤੇ ਉਸ ਨੂੰ ਚੱਕਰ ਆਉਣ ਅਤੇ ਨੀਂਦ ਆਉਣ ਲੱਗੀ।
ਅਰਿਸਟੋਫ਼ਨੇਸ ਦੀ ਕਾਮੇਡੀ "ਪੰਛੀ" ਵਿੱਚ, ਨਾਮਵਰ ਪੰਛੀ ਅਸਮਾਨ ਵਿੱਚ ਇੱਕ ਸ਼ਹਿਰ ਬਣਾਉਂਦੇ ਹਨ ਅਤੇ ਓਲੰਪਿਕ ਦੇਵਤਿਆਂ ਦੀ ਥਾਂ ਲੈਣ ਦੀ ਯੋਜਨਾ ਬਣਾਉਂਦੇ ਹਨ। ਸੰਦੇਸ਼ਵਾਹਕ ਦੇ ਰੂਪ ਵਿੱਚ ਆਈਰਿਸ, ਉਨ੍ਹਾਂ ਨੂੰ ਮਿਲਣ ਜਾਂਦਾ ਹੈ, ਪਰ ਉਹਨਾਂ ਦੇ ਨੇਤਾ ਪਿਸੇਟੇਰਸ, ਇੱਕ ਬਜ਼ੁਰਗ ਐਥੀਨੀਅਨ ਆਦਮੀ ਦੁਆਰਾ ਉਹਨਾਂ ਦਾ ਮਜ਼ਾਕ ਉਡਾਇਆ ਜਾਂਦਾ ਹੈ, ਉਹਨਾਂ ਦਾ ਅਪਮਾਨ ਕੀਤਾ ਜਾਂਦਾ ਹੈ ਅਤੇ ਉਹਨਾਂ ਨੂੰ ਬਲਾਤਕਾਰ ਦੀ ਧਮਕੀ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ। ਆਈਰਿਸ ਉਲਝਣ ਵਿੱਚ ਜਾਪਦਾ ਹੈ ਕਿ ਪੀਸੀਟੀਅਰਸ ਨੂੰ ਨਹੀਂ ਪਤਾ ਕਿ ਦੇਵਤੇ ਕੌਣ ਹਨ ਅਤੇ ਉਹ ਉਨ੍ਹਾਂ ਵਿੱਚੋਂ ਇੱਕ ਹੈ। ਪਿਸੇਟੇਰਸ ਫਿਰ ਉਸ ਨੂੰ ਦੱਸਦੀ ਹੈ ਕਿ ਪੰਛੀ ਹੁਣ ਦੇਵਤਾ ਹਨ, ਉਹ ਦੇਵਤੇ ਜਿਨ੍ਹਾਂ ਨੂੰ ਮਨੁੱਖਾਂ ਨੂੰ ਬਲੀ ਦੇਣਾ ਚਾਹੀਦਾ ਹੈ। ਜਦੋਂ ਪਿਸੇਟੇਰਸ ਉਸ ਨਾਲ ਬਲਾਤਕਾਰ ਕਰਨ ਦੀ ਧਮਕੀ ਦਿੰਦਾ ਹੈ, ਤਾਂ ਆਈਰਿਸ ਉਸ ਨੂੰ ਉਸ ਦੀ ਅਸ਼ਲੀਲ ਭਾਸ਼ਾ ਲਈ ਝਿਡ਼ਕਦਾ ਹੈ ਅਤੇ ਉਸ ਨੂੰ ਚੇਤਾਵਨੀ ਦਿੰਦਾ ਹੈ ਕਿ ਜ਼ੀਅਸ, ਜਿਸ ਨੂੰ ਉਹ ਆਪਣੇ ਪਿਤਾ ਵਜੋਂ ਦਰਸਾਉਂਦੀ ਹੈ, ਉਸ ਨਾਲ ਪੇਸ਼ ਆਵੇਗਾ ਅਤੇ ਉਸ ਨੂੰ ਭੁਗਤਾਨ ਕਰੇਗਾ।
ਆਈਰਿਸ ਵਰਜਿਲ ਦੇ "ਐਨੀਡ" ਵਿੱਚ ਵੀ ਕਈ ਵਾਰ ਦਿਖਾਈ ਦਿੰਦਾ ਹੈ, ਆਮ ਤੌਰ ਉੱਤੇ ਜੂਨੋ ਦੇ ਏਜੰਟ ਵਜੋਂ। ਕਿਤਾਬ 4 ਵਿੱਚ, ਜੂਨੋ ਉਸ ਨੂੰ ਰਾਣੀ ਡੀਡੋ ਦੇ ਸਿਰ ਤੋਂ ਵਾਲਾਂ ਦਾ ਤਾਲਾ ਤੋਡ਼ਨ ਲਈ ਭੇਜਦਾ ਹੈ, ਤਾਂ ਜੋ ਉਹ ਮਰ ਸਕੇ ਅਤੇ ਹੈਡੀਜ਼ ਵਿੱਚ ਦਾਖਲ ਹੋ ਸਕੇ। ਕਿਤਾਬ 5 ਵਿੱਚ, ਆਈਰਿਸ, ਇੱਕ ਟਰੋਜਨ ਔਰਤ ਦਾ ਰੂਪ ਲੈ ਕੇ, ਹੋਰ ਟਰੋਜਨ ਮਾਵਾਂ ਨੂੰ ਐਨੀਅਸ ਦੇ ਚਾਰ ਜਹਾਜ਼ਾਂ ਨੂੰ ਅੱਗ ਲਗਾਉਣ ਲਈ ਉਤੇਜਿਤ ਕਰਦੀ ਹੈ ਤਾਂ ਜੋ ਉਨ੍ਹਾਂ ਨੂੰ ਸਿਸਲੀ ਛੱਡਣ ਤੋਂ ਰੋਕਿਆ ਜਾ ਸਕੇ।
ਰੋਮਨ ਕਵੀ ਓਵਿਡ ਦੇ ਅਨੁਸਾਰ, ਰੋਮੁਲਸ ਨੂੰ ਦੇਵਤਾ ਦੇ ਰੂਪ ਵਿੱਚ ਪਰਿਭਾਸ਼ਿਤ ਕੀਤੇ ਜਾਣ ਤੋਂ ਬਾਅਦ, ਉਸ ਦੀ ਪਤਨੀ ਹਰਸੀਲੀਆ ਨੇ ਦੇਵਤਿਆਂ ਨੂੰ ਬੇਨਤੀ ਕੀਤੀ ਕਿ ਉਹ ਉਸ ਨੂੰ ਵੀ ਅਮਰ ਬਣ ਜਾਵੇ ਤਾਂ ਜੋ ਉਹ ਇੱਕ ਵਾਰ ਫਿਰ ਆਪਣੇ ਪਤੀ ਦੇ ਨਾਲ ਰਹਿ ਸਕੇ। ਜੂਨੋ ਨੇ ਉਸ ਦੀ ਬੇਨਤੀ ਸੁਣੀ ਅਤੇ ਉਸ ਨੂੰ ਆਈਰਿਸ ਹੇਠਾਂ ਭੇਜ ਦਿੱਤੀ। ਇੱਕ ਉਂਗਲੀ ਨਾਲ, ਆਈਰਿਸ ਨੇ ਹਰਸੀਲੀਆ ਨੂੰ ਛੂਹਿਆ ਅਤੇ ਉਸ ਨੂੰ ਇੱਕ ਅਮਰ ਦੇਵੀ ਵਿੱਚ ਬਦਲ ਦਿੱਤਾ। ਹਰਸੀਲੀਆ ਓਲੰਪਸ ਲਈ ਉੱਡੀ, ਜਿੱਥੇ ਉਹ ਇੱਕ ਹੋਰ ਬਣ ਗਈ ਅਤੇ ਉਸ ਨੂੰ ਆਪਣੇ ਪਤੀ ਨਾਲ ਹਮੇਸ਼ਾ ਲਈ ਰਹਿਣ ਦੀ ਆਗਿਆ ਦਿੱਤੀ ਗਈ।
ਟ੍ਰੋਜਨ ਯੁੱਧ।
ਸਟੈਸਿਨਸ ਦੁਆਰਾ ਗੁੰਮ ਹੋਏ ਮਹਾਂਕਾਵਿ "ਸਾਈਪਰੀਆ" ਦੇ ਅਨੁਸਾਰ, ਇਹ ਆਈਰਿਸ ਸੀ ਜਿਸ ਨੇ ਮੇਨਲਾਊਸ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ, ਜੋ ਕਿ ਕ੍ਰੈਟ ਲਈ ਰਵਾਨਾ ਹੋਇਆ ਸੀ, ਜਦੋਂ ਉਹ ਗਿਆ ਸੀ, ਸਪਾਰਟਾ ਵਿੱਚ ਕੀ ਵਾਪਰਿਆ ਸੀ, ਅਰਥਾਤ ਉਸਦੀ ਪਤਨੀ ਹੈਲਨ ਦਾ ਟਰੋਜਨ ਪ੍ਰਿੰਸ ਪੈਰਿਸ ਨਾਲ ਭੱਜਣ ਦੇ ਨਾਲ-ਨਾਲ ਹੈਲਨ ਦੇ ਭਰਾ ਕੈਸਟਰ ਦੀ ਮੌਤ।
ਆਈਰਿਸ ਦਾ ਅਕਸਰ "ਇਲਿਆਡ" ਵਿੱਚ ਇੱਕ ਬ੍ਰਹਮ ਸੰਦੇਸ਼ਵਾਹਕ ਵਜੋਂ ਜ਼ਿਕਰ ਕੀਤਾ ਜਾਂਦਾ ਹੈ, ਜਿਸ ਦਾ ਕਾਰਨ ਹੋਮਰ ਨੂੰ ਮੰਨਿਆ ਜਾਂਦਾ ਹੈ। ਹਾਲਾਂਕਿ, ਉਹ "ਓਡੀਸੀ" ਵਿੱਚ ਦਿਖਾਈ ਨਹੀਂ ਦਿੰਦੀ, ਜਿੱਥੇ ਉਸ ਦੀ ਭੂਮਿਕਾ ਹਰਮੀਜ਼ ਨਾਲ ਭਰੀ ਹੋਈ ਹੈ। ਹਰਮੀਜ਼ ਦੀ ਤਰ੍ਹਾਂ, ਆਈਰਿਸ ਵਿੱਚ ਇੱਕ ਕੈਡੂਸੀਅਸ ਜਾਂ ਖੰਭਾਂ ਵਾਲਾ ਸਟਾਫ ਹੁੰਦਾ ਹੈ। ਦੇਵਤਿਆਂ ਦੇ ਰਾਜਾ ਜ਼ੀਅਸ ਦੇ ਹੁਕਮ ਨਾਲ, ਉਹ ਸਟਿਕਸ ਨਦੀ ਤੋਂ ਪਾਣੀ ਦਾ ਇੱਕ ਪੱਥਰ ਚੁੱਕਦੀ ਹੈ, ਜਿਸ ਨਾਲ ਉਹ ਆਪਣੇ ਆਪ ਨੂੰ ਗਲਤ ਸਾਬਤ ਕਰਨ ਵਾਲੇ ਸਾਰੇ ਲੋਕਾਂ ਨੂੰ ਸੌਂਦੀ ਹੈ। ਕਿਤਾਬ xxiii ਵਿੱਚ, ਉਹ ਪੈਟ੍ਰੋਕਲਸ ਦੀ ਅੰਤਿਮ ਸੰਸਕਾਰ ਦੀ ਚਿਤਾ ਨੂੰ ਜਗਾਉਣ ਲਈ ਬੋਰਿਆਸ ਅਤੇ ਜ਼ੇਫਿਰਸ ਨੂੰ ਅਕਿਲਸ ਦੀ ਪ੍ਰਾਰਥਨਾ ਕਰਦੀ ਹੈ। ਆਖਰੀ ਕਿਤਾਬ ਵਿੱਚ, ਜ਼ਿਊਸ ਨੇ ਰਾਜਾ ਪ੍ਰਿਯਮ ਨੂੰ ਆਈਰਿਸ ਭੇਜੀ, ਤਾਂ ਜੋ ਉਸ ਨੂੰ ਦੱਸਿਆ ਜਾ ਸਕੇ ਕਿ ਉਸ ਨੂੰ ਇਕੱਲੇ ਅਕੀਅਨ ਕੈਂਪ ਵਿੱਚ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ ਅਤੇ ਆਪਣੇ ਮਾਰੇ ਗਏ ਪੁੱਤਰ ਹੈਕਟਰ ਦੀ ਲਾਸ਼ ਨੂੰ ਅਕੀਲੀਜ਼ ਤੋਂ ਫਿਰੌਤੀ ਦੇਣੀ ਚਾਹੀਦੀ ਹੈ। ਆਈਰਿਸ ਤੇਜ਼ੀ ਨਾਲ ਪ੍ਰਾਈਮ ਨੂੰ ਸੰਦੇਸ਼ ਪਹੁੰਚਾਉਂਦਾ ਹੈ ਅਤੇ ਓਲੰਪਸ ਵਿੱਚ ਵਾਪਸ ਆ ਜਾਂਦਾ ਹੈ।
ਹੋਰ ਮਿੱਥ.
ਹੋਮਰਿਕ ਭਜਨ ਟੂ ਅਪੋਲੋ" ਦੇ ਅਨੁਸਾਰ, ਜਦੋਂ ਲੇਟੋ ਆਪਣੇ ਜੁਡ਼ਵਾਂ ਬੱਚਿਆਂ ਅਪੋਲੋ ਅਤੇ ਆਰਟੇਮਿਸ ਨੂੰ ਜਨਮ ਦੇਣ ਤੋਂ ਪਹਿਲਾਂ ਪ੍ਰਸਵ ਵਿੱਚ ਸੀ, ਤਾਂ ਬੱਚੇ ਦੇ ਜਨਮ ਦੀ ਦੇਵੀ ਹੇਰਾ ਅਤੇ ਏਲੀਥੀਆ ਨੂੰ ਛੱਡ ਕੇ ਸਾਰੀਆਂ ਦੇਵੀਆਂ ਮੌਜੂਦ ਸਨ। ਉਸ ਦੀ ਲੇਬਰ ਦੇ ਨੌਵੇਂ ਦਿਨ, ਲੇਟੋ ਨੇ ਆਈਰਿਸ ਨੂੰ ਕਿਹਾ ਕਿ ਉਹ ਏਲੀਥੀਆ ਨੂੰ ਰਿਸ਼ਵਤ ਦੇਵੇ ਅਤੇ ਹੇਰਾ ਨੂੰ ਪਤਾ ਲਗਾਉਣ ਤੋਂ ਬਿਨਾਂ, ਉਸ ਦੇ ਬੱਚਿਆਂ ਨੂੰ ਜਨਮ ਦੇਣ ਵਿੱਚ ਉਸ ਦੀ ਮਦਦ ਮੰਗੇ। ਕੈਲੀਮਾਕਸ ਦੇ ਅਨੁਸਾਰ, ਆਇਰਿਸ ਨੇ ਏਰੇਸ ਦੇ ਨਾਲ, ਹੇਰਾ ਦੇ ਆਦੇਸ਼ਾਂ 'ਤੇ, ਸਾਰੇ ਸ਼ਹਿਰਾਂ ਅਤੇ ਹੋਰ ਥਾਵਾਂ ਨੂੰ ਗਰਭਵਤੀ ਲੇਟੋ ਨੂੰ ਛੱਡਣ ਅਤੇ ਉਸ ਦੀ ਪਨਾਹ ਤੋਂ ਇਨਕਾਰ ਕਰਨ ਦਾ ਆਦੇਸ਼ ਦਿੱਤਾ ਜਿੱਥੇ ਉਹ ਆਪਣੇ ਜੁਡ਼ਵਾਂ ਬੱਚਿਆਂ ਨੂੰ ਜਨਮ ਦੇ ਸਕਦੀ ਸੀ। ਐਸਟੇਰੀਆ, ਜੋ ਹੁਣ ਡੇਲੋਸ ਦੇ ਟਾਪੂ ਵਿੱਚ ਬਦਲ ਗਿਆ, ਨੇ ਲੇਟੋ ਨੂੰ ਪਨਾਹ ਦੀ ਪੇਸ਼ਕਸ਼ ਕੀਤੀ, ਆਈਰਿਸ ਨੇ ਉਸ ਨੂੰ ਸੂਚਿਤ ਕਰਨ ਲਈ ਵਾਪਸ ਹੇਰਾ ਨੂੰ ਉਡਾਣ ਭਰੀ ਕਿ ਲੇਟੋ ਨੂੰ ਐਸਟੇਰੀਆ ਦੇ ਕਾਰਨ ਪੈਦਾ ਕਰਨ ਦੀ ਆਗਿਆ ਦਿੱਤੀ ਗਈ ਸੀ, ਜਿਸ ਨੇ ਹੇਰਾ ਦੇ ਆਦੇਸ਼ਾਂ ਦੀ ਉਲੰਘਣਾ ਕੀਤੀ ਸੀ, ਅਤੇ ਹੇਰਾ ਦੇ ਨਾਲ ਆਪਣੀ ਸੀਟ ਲੈ ਲਈ।
ਅਪੋਲੋਨੀਅਸ ਰੋਡੀਅਸ ਦੇ ਅਨੁਸਾਰ, ਆਈਰਿਸ ਨੇ ਆਰਗੋਨਾਟਸ ਜ਼ੇਟਸ ਅਤੇ ਕੈਲਿਸ ਨੂੰ ਵਾਪਸ ਕਰ ਦਿੱਤਾ, ਜਿਨ੍ਹਾਂ ਨੇ ਹਾਰਪੀਜ਼ ਦਾ ਸਟ੍ਰੌਫੈਡ ("ਮੋਡ਼ ਦੇ ਟਾਪੂ") ਤੱਕ ਪਿੱਛਾ ਕੀਤਾ ਸੀ। ਭਰਾਵਾਂ ਨੇ ਰਾਖਸ਼ਾਂ ਨੂੰ ਫ਼ਿਨਿਅਸ ਨਬੀ ਦੇ ਤਸੀਹੇ ਤੋਂ ਭਜਾ ਦਿੱਤਾ ਸੀ, ਪਰ ਆਈਰਿਸ ਦੀ ਬੇਨਤੀ 'ਤੇ ਉਨ੍ਹਾਂ ਨੂੰ ਨਹੀਂ ਮਾਰਿਆ, ਜਿਸ ਨੇ ਵਾਅਦਾ ਕੀਤਾ ਸੀ ਕਿ ਫ਼ਿਨਿਅਸ ਨੂੰ ਫਿਰ ਤੋਂ ਹਾਰਪੀਜ਼ ਤੋਂ ਪਰੇਸ਼ਾਨ ਨਹੀਂ ਕੀਤਾ ਜਾਵੇਗਾ।
ਜਦੋਂ ਥੀਬਸ ਦੇ ਰਾਜਾ ਕ੍ਰਿਓਨ ਨੇ ਥੀਸਸ ਦੇ ਵਿਰੁੱਧ ਆਪਣੇ ਹਥਿਆਰ ਚੁੱਕਣ ਵਾਲੇ ਮਰੇ ਹੋਏ ਆਰਗਿਵ ਸੈਨਿਕਾਂ ਨੂੰ ਦਫ਼ਨਾਉਣ ਤੋਂ ਮਨ੍ਹਾ ਕਰ ਦਿੱਤਾ, ਤਾਂ ਹੇਰਾ ਨੇ ਆਈਰਿਸ ਨੂੰ ਤ੍ਰੇਲ ਅਤੇ ਐਂਬਰੋਸੀਆ ਨਾਲ ਆਪਣੀਆਂ ਲਾਸ਼ਾਂ ਨੂੰ ਨਮੀ ਦੇਣ ਦਾ ਆਦੇਸ਼ ਦਿੱਤਾ।
ਇੱਕ ਘੱਟ ਜਾਣੇ-ਪਛਾਣੇ ਬਿਰਤਾਂਤ ਵਿੱਚ, ਆਈਰਿਸ ਇੱਕ ਵਾਰ ਵਿਅੰਗ ਕਰਨ ਵਾਲਿਆਂ ਦੁਆਰਾ ਬਲਾਤਕਾਰ ਦੇ ਨੇਡ਼ੇ ਆ ਗਈ ਸੀ ਜਦੋਂ ਉਸਨੇ ਸ਼ਾਇਦ ਹੇਰਾ ਦੇ ਇਸ਼ਾਰੇ 'ਤੇ ਡਾਇਓਨਿਸਸ ਦੀ ਪੂਜਾ ਨੂੰ ਵਿਗਾਡ਼ਨ ਦੀ ਕੋਸ਼ਿਸ਼ ਕੀਤੀ ਸੀ। ਪੰਜਵੀਂ ਸਦੀ ਈ. ਪੂ. ਦੀਆਂ ਲਗਭਗ ਪੰਦਰਾਂ ਕਾਲੀਆਂ ਅਤੇ ਲਾਲ-ਅੰਕ ਵਾਲੀਆਂ ਫੁੱਲਾਂ ਦੇ ਫੁੱਲਾਂ ਦੀਆਂ ਪੇਂਟਿੰਗਾਂ ਵਿੱਚ ਕਿਹਾ ਗਿਆ ਹੈ ਕਿ ਜਦੋਂ ਉਹ ਬਲੀਦਾਨ ਵਿੱਚ ਦਖ਼ਲ ਦੇਣ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰਦੀ ਹੈ ਤਾਂ ਵਿਅੰਗ ਕਰਨ ਵਾਲੇ ਜਾਂ ਤਾਂ ਡਰਾਉਣੇ ਢੰਗ ਨਾਲ ਉਸ ਵੱਲ ਵਧਦੇ ਹਨ ਜਾਂ ਉਸ ਨੂੰ ਫਡ਼ ਲੈਂਦੇ ਹਨ। ਇੱਕ ਹੋਰ ਕੱਪ ਵਿੱਚ, ਆਈਰਿਸ ਨੂੰ ਵਿਅੰਗ ਕਰਨ ਵਾਲਿਆਂ ਦੁਆਰਾ ਹਮਲਾ ਕੀਤੇ ਜਾਣ ਨੂੰ ਦਰਸਾਇਆ ਗਿਆ ਹੈ, ਜੋ ਸਪੱਸ਼ਟ ਤੌਰ 'ਤੇ ਆਈਰਿਸ ਨੂੰ ਡਾਇਓਨਿਸਸ ਦੀ ਜਗਵੇਦੀ ਤੋਂ ਬਲੀਦਾਨ ਦਾ ਮੀਟ ਚੋਰੀ ਕਰਨ ਤੋਂ ਰੋਕਣ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰ ਰਹੇ ਹਨ, ਜੋ ਕਿ ਦ੍ਰਿਸ਼ ਵਿੱਚ ਮੌਜੂਦ ਹੈ। ਦੂਜੇ ਪਾਸੇ, ਵਿਅੰਗ ਕਰਨ ਵਾਲੇ ਹੇਰਾ ਉੱਤੇ ਹਮਲਾ ਕਰ ਰਹੇ ਹਨ, ਜੋ ਹਰਮੀ ਅਤੇ ਹੈਰਕਲਾਂ ਦੇ ਵਿਚਕਾਰ ਖਡ਼੍ਹਾ ਹੈ। ਪ੍ਰਾਚੀਨ ਨਾਟਕਕਾਰ ਅਕੀਅਸ ਨੇ "ਆਈਰਿਸ" ਲਿਖਿਆ, ਜੋ ਹੁਣ ਗੁੰਮ ਹੋ ਗਿਆ ਵਿਅੰਗਾਤਮਕ ਨਾਟਕ ਹੈ, ਜੋ ਸ਼ਾਇਦ ਉਨ੍ਹਾਂ ਫੁੱਲਾਂ ਦੇ ਵਿਸ਼ੇ ਦਾ ਸਰੋਤ ਹੋ ਸਕਦਾ ਹੈ।
ਯੂਰੀਪਾਈਡਸ ਦੇ ਨਾਟਕ "ਹੈਰਕਲਸ ਗੰਡ ਮੈਡ" ਵਿੱਚ, ਆਈਰਿਸ ਪਾਗਲਪਨ ਅਤੇ ਪਾਗਲਪਨ ਦੀ ਦੇਵੀ ਲਿਸਾ ਦੇ ਨਾਲ ਦਿਖਾਈ ਦਿੰਦਾ ਹੈ, ਜੋ ਕਿ ਪਾਗਲਪਨ ਦੇ ਨਾਲ ਹੈਰਕਲਾਂ ਨੂੰ ਸਰਾਪ ਦਿੰਦਾ ਹੈ ਜਿਸ ਵਿੱਚ ਉਹ ਆਪਣੇ ਤਿੰਨ ਪੁੱਤਰਾਂ ਅਤੇ ਆਪਣੀ ਪਤਨੀ ਮੇਗਾਰਾ ਨੂੰ ਮਾਰ ਦਿੰਦਾ ਹੈ। ਆਈਰਿਸ ਨੇ ਜ਼ੀਅਸ ਅਤੇ ਹੇਰਾ ਦਾ ਬਿਸਤਰਾ ਵੀ ਤਿਆਰ ਕੀਤਾ।
ਪੂਜਾ ਕਰੋ।
ਪੰਥ.
ਯੂਨਾਨੀਆਂ ਦੇ ਹੋਰ ਪ੍ਰਮੁੱਖ ਸੰਦੇਸ਼ਵਾਹਕ ਦੇਵਤਾ ਦੇ ਉਲਟ, ਹਰਮਿਸ, ਆਈਰਿਸ ਨੇ ਪ੍ਰਾਚੀਨ ਯੂਨਾਨੀ ਧਰਮ ਵਿੱਚ ਵੱਡੀ ਭੂਮਿਕਾ ਨਹੀਂ ਨਿਭਾਈ ਅਤੇ ਘੱਟ ਹੀ ਪੂਜਾ ਕੀਤੀ ਜਾਂਦੀ ਸੀ। ਇੱਥੇ ਕੋਈ ਜਾਣੇ-ਪਛਾਣੇ ਮੰਦਰ, ਮੰਦਰ ਜਾਂ ਆਈਰਿਸ ਦੇ ਪਨਾਹਗਾਹਾਂ ਜਾਂ ਉਸ ਦੇ ਸਨਮਾਨ ਵਿੱਚ ਮਨਾਏ ਜਾਣ ਵਾਲੇ ਤਿਉਹਾਰ ਨਹੀਂ ਹਨ। ਜਦੋਂ ਕਿ ਉਸ ਨੂੰ ਅਕਸਰ ਫੁੱਲਾਂ ਦੇ ਫੁੱਲਾਂ ਅਤੇ ਬੇਸ-ਰਿਲੀਫ ਵਿੱਚ ਦਰਸਾਇਆ ਜਾਂਦਾ ਹੈ, ਪ੍ਰਾਚੀਨ ਕਾਲ ਦੌਰਾਨ ਕੁਝ ਮੂਰਤੀਆਂ ਆਈਰਿਸ ਦੀਆਂ ਬਣੀਆਂ ਜਾਣੀਆਂ ਜਾਂਦੀਆਂ ਹਨ। ਹਾਲਾਂਕਿ ਉਸ ਨੂੰ ਏਥਨਜ਼ ਵਿੱਚ ਪਾਰਥੇਨੌਨ ਦੇ ਪੱਛਮੀ ਪੈਡੀਮੈਂਟ ਉੱਤੇ ਮੂਰਤੀ ਵਿੱਚ ਦਰਸਾਇਆ ਗਿਆ ਸੀ।
ਆਈਰਿਸ ਘੱਟੋ ਘੱਟ ਕੁਝ ਮਾਮੂਲੀ ਪੂਜਾ ਦਾ ਉਦੇਸ਼ ਜਾਪਦਾ ਹੈ, ਪਰ ਉਸ ਦੇ ਪੰਥ ਦਾ ਇੱਕੋ ਇੱਕ ਨਿਸ਼ਾਨ ਹੈ ਜੋ "ਰਾਤ ਦੇ ਖਾਣੇ ਦੇ ਵਿਦਵਾਨਾਂ" ਵਿੱਚ ਐਥੇਨੀਅਸ ਦੁਆਰਾ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ ਹੈ ਕਿ ਡੇਲੋਸ ਦੇ ਲੋਕਾਂ ਨੇ ਆਈਰਿਸ ਨੂੰ ਕੁਰਬਾਨ ਕਰ ਦਿੱਤਾ, ਉਸ ਨੂੰ "ਬੇਸੀਨੀਆ" ਨਾਮਕ ਚੀਜ਼ਕੇਕ ਦੀ ਪੇਸ਼ਕਸ਼ ਕੀਤੀ, ਜੋ ਕਿ ਕਣਕ ਦੇ ਆਟੇ, ਸੂਟ ਅਤੇ ਹਨੀ ਦਾ ਇੱਕ ਕਿਸਮ ਦਾ ਕੇਕ ਹੈ, ਜੋ ਇਕੱਠੇ ਉਬਾਲੇ ਗਏ ਹਨ।
ਉਪ-ਚਿੱਤਰ.
ਆਈਰਿਸ ਦੇ ਕਈ ਕਾਵਿਕ ਸਿਰਲੇਖ ਅਤੇ ਉਪਨਾਮੇ ਸਨ, ਜਿਨ੍ਹਾਂ ਵਿੱਚ "ਕ੍ਰਾਇਸੋਪਟਰੋਸ" ("ਸੁਨਹਿਰੀ ਖੰਭਾਂ ਵਾਲਾ"), "ਪੋਡਾਸ ōkea" ("ਤੇਜ਼ ਪੈਰ ਵਾਲਾ") ਜਾਂ "ਪੋਡੇਨੇਮੋਸ ōkea" ("ਹਵਾ-ਸਵਿਫਟ ਪੈਰ ਵਾਲਾ"), "roscida" ("ਡੇਵੀ", ਲਾਤੀਨੀ), ਅਤੇ "ਥੌਮੈਂਟੀਅਸ" ਜਾਂ "ਥੌਮੈਂਟੀਸ" (, ", ਥੌਮਾਸ ਦੀ ਧੀ, ਅਦਭੁਤ"), "ਐਲੋਪਸ" ("ਤੂਫਾਨ-ਪੈਰ ਵਾਲਾ, ਤੂਫਾਨ-ਸਵਿਫਟ") ਸ਼ਾਮਲ ਹਨ। ਉਸਨੇ ਆਪਣੇ ਘਡ਼ਾ ਨਾਲ ਬੱਦਲਾਂ ਨੂੰ ਪਾਣੀ ਵੀ ਦਿੱਤਾ, ਸਮੁੰਦਰ ਤੋਂ ਪਾਣੀ ਪ੍ਰਾਪਤ ਕੀਤਾ।
ਨੁਮਾਇੰਦਗੀ.
ਆਈਰਿਸ ਨੂੰ ਜਾਂ ਤਾਂ ਸਤਰੰਗੀ ਧਨੁਸ਼ ਦੇ ਰੂਪ ਵਿੱਚ ਜਾਂ ਇੱਕ ਸੁੰਦਰ ਨੌਜਵਾਨ ਕੁਡ਼ੀ ਦੇ ਰੂਪ ਵਿੱਚ ਦਰਸਾਇਆ ਜਾਂਦਾ ਹੈ ਜਿਸ ਦੇ ਮੋਢਿਆਂ ਉੱਤੇ ਖੰਭ ਹੁੰਦੇ ਹਨ। ਇੱਕ ਦੇਵੀ ਦੇ ਰੂਪ ਵਿੱਚ, ਆਈਰਿਸ ਸੰਚਾਰ, ਸੰਦੇਸ਼ਾਂ, ਸਤਰੰਗੀ ਅਤੇ ਨਵੇਂ ਯਤਨਾਂ ਨਾਲ ਜੁਡ਼ਿਆ ਹੋਇਆ ਹੈ। ਸਤਰੰਗੀ ਧਨੁਸ਼ ਦੇ ਇਸ ਰੂਪ ਨੂੰ ਇੱਕ ਵਾਰ ਸਵਰਗ ਅਤੇ ਧਰਤੀ ਨਾਲ ਜੋਡ਼ਨ ਵਜੋਂ ਦਰਸਾਇਆ ਗਿਆ ਸੀ।
ਕੁੱਝ ਗ੍ਰੰਥਾਂ ਵਿੱਚ ਉਸ ਨੂੰ ਕਈ ਰੰਗਾਂ ਦਾ ਕੋਟ ਪਹਿਨਦੇ ਹੋਏ ਦਰਸਾਇਆ ਗਿਆ ਹੈ। ਇਸ ਕੋਟ ਨਾਲ ਉਹ ਅਸਲ ਵਿੱਚ ਸਤਰੰਗੀ ਕਮਾਨ ਬਣਾਉਂਦੀ ਹੈ ਜਿਸ ਉੱਤੇ ਉਹ ਸਵਾਰੀ ਕਰਦੀ ਹੈ ਤਾਂ ਜੋ ਉਹ ਇੱਕ ਜਗ੍ਹਾ ਤੋਂ ਦੂਜੀ ਜਗ੍ਹਾ ਪਹੁੰਚ ਸਕੇ। ਆਈਰਿਸ ਦੇ ਖੰਭ ਇੰਨੇ ਸੁੰਦਰ ਦੱਸੇ ਜਾਂਦੇ ਸਨ ਕਿ ਉਹ ਇੱਕ ਕਾਲੀ ਗੁਫਾ ਨੂੰ ਵੀ ਜਗਾ ਸਕਦੀ ਸੀ, ਜੋ ਕਿ ਉਸ ਦੀ ਸੋਮਨਸ ਦੀ ਫੇਰੀ ਦੀ ਕਹਾਣੀ ਤੋਂ ਅਲਸੀਓਨ ਨੂੰ ਇੱਕ ਸੰਦੇਸ਼ ਦੇਣ ਲਈ ਵੇਖੀ ਜਾ ਸਕਦੀ ਹੈ।
ਜਦੋਂ ਕਿ ਆਈਰਿਸ ਮੁੱਖ ਤੌਰ 'ਤੇ ਸੰਚਾਰ ਅਤੇ ਸੰਦੇਸ਼ਾਂ ਨਾਲ ਜੁਡ਼ੀ ਹੋਈ ਸੀ, ਇਹ ਵੀ ਮੰਨਿਆ ਜਾਂਦਾ ਸੀ ਕਿ ਉਹ ਮਨੁੱਖਾਂ ਦੀਆਂ ਪ੍ਰਾਰਥਨਾਵਾਂ ਨੂੰ ਪੂਰਾ ਕਰਨ ਵਿੱਚ ਸਹਾਇਤਾ ਕਰਦੀ ਹੈ, ਜਾਂ ਤਾਂ ਉਹਨਾਂ ਨੂੰ ਖੁਦ ਪੂਰਾ ਕਰਕੇ ਜਾਂ ਉਹਨਾਂ ਨੂੰ ਹੋਰ ਦੇਵਤਿਆਂ ਦੇ ਧਿਆਨ ਵਿੱਚ ਲਿਆ ਕੇ।

,
ਆਇਓਨਿਸ ਕੋਂਟੋਇਆਨਿਸ

ਇਓਨਿਸ ਕੋਂਟੋਇਆਨਿਸ (ਜਨਮ ਜਨਵਰੀ 1972) ਇੱਕ ਯੂਨਾਨੀ ਗਣਿਤ ਸ਼ਾਸਤਰੀ ਅਤੇ ਸੂਚਨਾ ਸਿਧਾਂਤਕਾਰ ਹੈ। ਉਹ ਕੈਂਬ੍ਰਿਜ ਯੂਨੀਵਰਸਿਟੀ ਦੇ ਸ਼ੁੱਧ ਗਣਿਤ ਅਤੇ ਗਣਿਤਿਕ ਅੰਕਡ਼ਾ ਵਿਭਾਗ ਵਿੱਚ ਅੰਕਡ਼ਾ ਪ੍ਰਯੋਗਸ਼ਾਲਾ ਦੇ ਨਾਲ ਸੰਚਾਲਨ ਖੋਜ ਲਈ ਗਣਿਤ ਦੇ ਚਰਚਿਲ ਪ੍ਰੋਫੈਸਰ ਹਨ। ਉਹ ਡਾਰਵਿਨ ਕਾਲਜ, ਕੈਂਬ੍ਰਿਜ ਦਾ ਇੱਕ ਫੈਲੋ, ਸੂਚਨਾ ਇੰਜੀਨੀਅਰਿੰਗ ਡਿਵੀਜ਼ਨ, ਕੈਂਬ੍ਰਿਜ ਦਾ ਇੱਕ ਮਾਨਤਾ ਪ੍ਰਾਪਤ ਮੈਂਬਰ, ਖੋਜ ਅਤੇ ਟੈਕਨੋਲੋਜੀ-ਹੇਲਸ ਲਈ ਫਾਊਂਡੇਸ਼ਨ ਦਾ ਇੱਕ ਖੋਜ ਫੈਲੋ, ਰੌਬਿਨਸਨ ਕਾਲਜ, ਕੈਂਬ੍ਰਿਜ ਦਾ ਇੱਕ ਸੀਨੀਅਰ ਮੈਂਬਰ ਅਤੇ ਰੋਲੋ ਡੇਵਿਡਸਨ ਟਰੱਸਟ ਦਾ ਇੱਕ ਟਰੱਸਟੀ ਵੀ ਹੈ।
ਉਹਨਾਂ ਦੀਆਂ ਖੋਜ ਰੁਚੀਆਂ ਸੂਚਨਾ ਥਿਊਰੀ, ਸੰਭਾਵਨਾ ਅਤੇ ਅੰਕਡ਼ਿਆਂ ਵਿੱਚ ਹਨ, ਜਿਸ ਵਿੱਚ ਡੇਟਾ ਸੰਕੁਚਨ, ਬਾਇਓਇਨਫਰਮੈਟਿਕਸ, ਨਿਊਰੋਸਾਇੰਸ, ਮਸ਼ੀਨ ਲਰਨਿੰਗ ਅਤੇ ਮੁੱਖ ਜਾਣਕਾਰੀ-ਸਿਧਾਂਤਕ ਵਿਚਾਰਾਂ ਅਤੇ ਨਤੀਜੇ ਸੰਭਾਵਨਾ ਥਿਊਰੀ ਅਤੇ ਐਡਿਟਿਵ ਕੰਬੀਨੇਟੋਰਿਕਸ ਵਿੱਚ ਉਹਨਾਂ ਦੇ ਉਪਯੋਗ ਸ਼ਾਮਲ ਹਨ।
ਅਕਾਦਮਿਕ ਜੀਵਨੀ।
ਕੋਂਟੋਇਆਨਿਸ ਨੇ ਬੀ. ਏ. ਪ੍ਰਾਪਤ ਕੀਤਾ।ਐਸ. ਇੰਪੀਰੀਅਲ ਕਾਲਜ, ਲੰਡਨ ਯੂਨੀਵਰਸਿਟੀ (1992) ਤੋਂ ਗਣਿਤ ਵਿੱਚ, ਉਸਨੇ ਕੈਂਬ੍ਰਿਜ ਯੂਨੀਵਰਸਿਟੀ ਸ਼ੁੱਧ ਗਣਿਤ ਟ੍ਰਾਈਪੋਸ (1993) ਦੇ ਭਾਗ III ਵਿੱਚ ਇੱਕ ਵਿਸ਼ੇਸ਼ਤਾ ਪ੍ਰਾਪਤ ਕੀਤੀ, ਅਤੇ ਉਸਨੇ ਇੱਕ ਐਮ.ਐਸ. ਅੰਕਡ਼ਾ (1997) ਅਤੇ ਇੱਕ ਪੀਐਚ.ਡੀ. ਇਲੈਕਟ੍ਰੀਕਲ ਇੰਜੀਨੀਅਰਿੰਗ (1998) ਵਿੱਚ, ਦੋਵੇਂ ਸਟੈਨਫੋਰਡ ਯੂਨੀਵਰਸਿਟੀ ਤੋਂ। 1998 ਅਤੇ 2018 ਦੇ ਵਿਚਕਾਰ ਉਨ੍ਹਾਂ ਨੇ ਪਰਡਿਊ ਯੂਨੀਵਰਸਿਟੀ, ਬਰਾਊਨ ਯੂਨੀਵਰਸਿਟੀ, ਕੋਲੰਬੀਆ ਯੂਨੀਵਰਸਿਟੀ ਅਤੇ ਏਥਨਜ਼ ਯੂਨੀਵਰਸਿਟੀ ਆਫ਼ ਇਕਨਾਮਿਕਸ ਐਂਡ ਬਿਜ਼ਨਸ ਵਿੱਚ ਪਡ਼ਾਇਆ। ਜਨਵਰੀ 2018 ਵਿੱਚ ਉਹ ਕੈਂਬ੍ਰਿਜ ਯੂਨੀਵਰਸਿਟੀ ਵਿੱਚ ਸੂਚਨਾ ਇੰਜੀਨੀਅਰਿੰਗ ਡਿਵੀਜ਼ਨ ਵਿੱਚ ਸੂਚਨਾ ਅਤੇ ਸੰਚਾਰ ਦੇ ਪ੍ਰੋਫੈਸਰ ਅਤੇ ਸਿਗਨਲ ਪ੍ਰੋਸੈਸਿੰਗ ਅਤੇ ਸੰਚਾਰ ਪ੍ਰਯੋਗਸ਼ਾਲਾ ਦੇ ਮੁਖੀ ਵਜੋਂ ਸ਼ਾਮਲ ਹੋਏ। ਜੂਨ 2020 ਤੋਂ ਉਹ ਕੈਮਬ੍ਰਿਜ ਯੂਨੀਵਰਸਿਟੀ ਦੇ ਸ਼ੁੱਧ ਗਣਿਤ ਅਤੇ ਗਣਿਤਿਕ ਅੰਕਡ਼ਾ ਵਿਭਾਗ ਵਿੱਚ ਅੰਕਡ਼ਾ ਪ੍ਰਯੋਗਸ਼ਾਲਾ ਦੇ ਨਾਲ ਰਹੇ ਹਨ, ਜਿੱਥੇ ਉਹ ਗਣਿਤ ਵਿੱਚ ਚਰਚਿਲ ਚੇਅਰ ਰੱਖਦੇ ਹਨ।

,
ਕੈਲਗਰੀ ਰੋਲਰ ਡਰਬੀ

ਕੈਲਗਰੀ ਰੋਲਰ ਡਰਬੀ ਇੱਕ ਗੈਰ-ਮੁਨਾਫਾ ਔਰਤਾਂ ਦੀ ਫਲੈਟ-ਟਰੈਕ ਰੋਲਰ ਡਰਬੀ ਲੀਗ ਹੈ ਜੋ ਕੈਲਗਰੀ, ਅਲਬਰਟਾ, ਕੈਨੇਡਾ ਵਿੱਚ ਅਧਾਰਤ ਹੈ। ਕੈਲਗਰੀ ਰੋਲਰ ਡਰਬੀ ਔਰਤਾਂ ਦੀ ਫਲੈਟ ਟਰੈਕ ਡਰਬੀ ਐਸੋਸੀਏਸ਼ਨ (ਡਬਲਯੂ. ਐੱਫ. ਟੀ. ਡੀ. ਏ.) ਦੀ ਮੈਂਬਰ ਹੈ।
ਇਤਿਹਾਸ ਅਤੇ ਬਣਤਰ.
ਕੈਲਗਰੀ ਰੋਲਰ ਡਰਬੀ ਨੂੰ ਅਸਲ ਵਿੱਚ 2006 ਵਿੱਚ ਸੈਂਡਸਟੌਨ ਸਿਟੀ ਰੋਲਰ ਗਰਲਜ਼ ਵਜੋਂ ਬਣਾਇਆ ਗਿਆ ਸੀ, ਅਤੇ ਅਗਲੇ ਸਾਲ ਕੈਲਗਰੀ ਰੋਲਰ ਡਰਬੀ ਐਸੋਸੀਏਸ਼ਨ ਵਜੋਂ ਪੁਨਰਗਠਨ ਕੀਤਾ ਗਿਆ ਸੀ। ਲੀਗ ਸਕੇਟਰ ਦੀ ਮਲਕੀਅਤ ਅਤੇ ਸਕੇਟਰ ਦੁਆਰਾ ਸੰਚਾਲਿਤ ਹੈ ਅਤੇ ਇੱਕ ਗੈਰ-ਮੁਨਾਫਾ ਸੰਗਠਨ ਹੈ। ਅਪ੍ਰੈਲ 2018 ਵਿੱਚ ਲੀਗ ਨੇ ਇੱਕ ਰੀਬ੍ਰਾਂਡ ਦੀ ਘੋਸ਼ਣਾ ਕੀਤੀ ਅਤੇ ਆਪਣੇ ਨਾਮ ਤੋਂ "ਐਸੋਸੀਏਸ਼ਨ" ਨੂੰ ਹਟਾ ਦਿੱਤਾ, ਅਤੇ ਇੱਕ ਅੱਪਡੇਟ ਕੀਤਾ ਲੋਗੋ ਪੇਸ਼ ਕੀਤਾ।

In [ ]:
corpus = " ".join(df.index.astype(str).tolist())
type(corpus), len(corpus), print(corpus[:1000])

ਵੱਡਾ (ਬੇਓਨਸੇ ਗੀਤ)

"ਵੱਡਾ" (ਵੱਡੇ ਅੱਖਰ ਵਿੱਚ ਸ਼ੈਲੀਬੱਧ) ਅਮਰੀਕੀ ਗਾਇਕ ਬਿਓਨਸੇ ਦੁਆਰਾ 2019 ਦੀ ਐਲਬਮ "" ਤੋਂ ਇੱਕ ਗੀਤ ਹੈ ਅਤੇ 2020 ਦੀ ਫਿਲਮ "" ਬਲੈਕ ਇਜ਼ ਕਿੰਗ "" ਵਿੱਚ ਪ੍ਰਦਰਸ਼ਿਤ ਕੀਤਾ ਗਿਆ ਹੈ।
ਪਿਛੋਕਡ਼.
ਇਹ ਗੀਤ ਬਿਓਨਸੇ ਦੇ ਸਟੂਡੀਓ ਵਿੱਚ ਇੱਕ ਲਿਖਣ ਕੈਂਪ ਵਿੱਚ ਲਿਖਿਆ ਗਿਆ ਸੀ ਅਤੇ ਬ੍ਰਿਟਿਸ਼ ਗਾਇਕ-ਗੀਤਕਾਰ ਰੇਅ ਅਤੇ ਯੂ. ਐੱਸ. ਗੀਤਕਾਰ ਸਟੇਸੀ ਬਾਰਥੇ ਨਾਲ ਇੱਕ ਬੰਧਨ ਦੇ ਕਾਰਨ ਬਣਾਇਆ ਗਿਆ ਸੀ। ਰੇ ਨੇ ਬੀਬੀਸੀ ਨਿਊਜ਼ਬੀਟ ਨੂੰ ਦੱਸਿਆਃ "ਮੈਨੂੰ ਯਾਦ ਹੈ ਕਿ ਅਸੀਂ ਦੋਵੇਂ ਸੱਚਮੁੱਚ ਇੱਕ ਹਨੇਰੇ, ਉਦਾਸ ਜਗ੍ਹਾ ਵਿੱਚ ਸੀ ਅਤੇ ਅਸੀਂ ਆਪਣੇ ਆਪ ਨੂੰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਉਣ ਲਈ ਕੁਝ ਬਣਾਉਣਾ ਚਾਹੁੰਦੇ ਸੀ। ਅਸੀਂ ਸ਼ਾਇਦ ਦੋ ਜਾਂ ਤਿੰਨ ਘੰਟੇ ਇਸ ਉੱਤੇ ਬਿਤਾਏ। ਇਹ 3 ਏ ਸੀ।ਐਮ. ਅਤੇ ਮੈਨੂੰ ਯਾਦ ਹੈ ਕਿ ਬਿਓਨਸੇ ਦੀ ਟੀਮ ਆਈ ਅਤੇ ਸੁਣਿਆ ਕਿ ਅਸੀਂ ਹੁਣ ਤੱਕ ਕੀ ਬਣਾਇਆ ਹੈ ਅਤੇ ਪੂਰੀ ਤਰ੍ਹਾਂ ਘਬਰਾ ਗਏ ਹਾਂ। ਇਹ ਸ਼ਾਨਦਾਰ ਸੀ।"ਰੇ ਨੇ ਅਧਿਕਾਰਤ ਚਾਰਟ ਨੂੰ ਇਹ ਵੀ ਦੱਸਿਆਃ" ਮੈਂ ਬਹੁਤ ਸਾਰੇ ਗੀਤ ਲਿਖੇ-ਮੈਂ ਇੱਕ ਸ਼ਿਫਟ ਵਿੱਚ ਪਾ ਦਿੱਤਾ। ਪਰ [ਬੇਓਨਸੇ] ਨੂੰ ਵੱਡੇ ਨਾਲ ਪਿਆਰ ਹੋ ਗਿਆ।"ਬਿਓਨਸੇ ਨੇ ਰੇਅ ਨੂੰ ਦੱਸਿਆ ਕਿ 2019 ਦੇ" "ਦਿ ਲਾਇਨ ਕਿੰਗ" "ਯੂਰਪੀਅਨ ਪ੍ਰੀਮੀਅਰ ਵਿੱਚ ਐਲਬਮ ਦਾ ਪਹਿਲਾ ਗੀਤ" "ਵੱਡਾ" "ਹੋਵੇਗਾ, ਅਤੇ ਜਿਵੇਂ ਕਿ ਵੀਡੀਓ ਵਿੱਚ ਫਡ਼ਿਆ ਗਿਆ ਹੈ, ਉਸ ਦੀ ਪ੍ਰਤੀਕਿਰਿਆ ਵਾਇਰਲ ਹੋ ਗਈ। ਰੇ ਨੇ ਟਵੀਟ ਕੀਤਾ,

(str, 308256616, None)

In [39]:
list(df.index[:5])
df.index[0] in corpus
df.index[1] in corpus

True

In [1]:
import contractions
text = "I can't find Sarah's keys, and she won't be at her brother's house until it's dark."
expanded_text = contractions.fix(text)
print(expanded_text)

I cannot find Sarah's keys, and she will not be at her brother's house until it is dark.

In [2]:
def cont_to_exp(x):
    if type(x) is str:
        x = x.replace('\\','')
        x = contractions.fix(x)
        return x
    else:
        return x