In [113]:
import sys
print(sys.executable)

/usr/bin/python3

In [114]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as py
import cufflinks as cf
from plotly.offline import iplot
%matplotlib inline

In [115]:
py.offline.init_notebook_mode(connected=True)
cf.go_offline()

In [116]:
dataset = "/home/ihtgoot/college_project/NLP_project/NEW/cleaned_shloks.csv"
df = pd.read_csv(dataset,index_col=0)

In [117]:
df.head(10)

                                                     shlok_text
shlok_number
1             1 ੧ਓ ਸਿਤ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਿਨਰਭਉ ਿਨਰਵੈਰੁ ਅਕਾਲ ਮੂ...
2                                                         ਜਪੁ ॥
3                                        ਆਿਦ ਸਚ ੁ ਜੁਗਾਿਦ ਸਚ ੁ ॥
4                                ਹੈ ਭੀ ਸਚ ੁਨਾਨਕ ਹਸੋ ੀ ਭੀ ਸਚ ੁ ॥
5                                                           ੧ ॥
6                             ਸੋਚੈ ਸੋਿਚ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥
7                         ਚਪੁ ੈ ਚਪੁ ਨ ਹੋਵਈ ਜੇ ਲਾਇ ਰਹਾ ਿਲਵ ਤਾਰ ॥
8                         ਭੁਿਖਆ ਭੁਖ ਨ ਉਤਰੀ ਜੇ ਬਨੰ ਾ ਪੁਰੀਆ ਭਾਰ ॥
9                          ਸਹਸ ਿਸਆਣਪਾ ਲਖ ਹੋਿਹ ਤ ਇਕ ਨ ਚਲੈ ਨਾਿਲ ॥
10                         ਿਕਵ ਸਿਚਆਰਾ ਹੋਈਐ ਿਕਵ ਕੂੜੈ ਤੁਟੈ ਪਾਿਲ ॥

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86064 entries, 1 to 86064
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   shlok_text  86064 non-null  object
dtypes: object(1)
memory usage: 1.3+ MB

In [119]:
df.isnull().sum()

shlok_text    0
dtype: int64

In [120]:
print(f"no of rows : {len(df)}")
df.shape[0]

no of rows : 86064

86064

In [121]:
df.shape

(86064, 1)

In [122]:
print(' '.join(df['shlok_text'].tolist()[:5]))

1 ੧ਓ ਸਿਤ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਿਨਰਭਉ ਿਨਰਵੈਰੁ ਅਕਾਲ ਮੂਰਿਤ ਅਜੂਨੀ ਸੈਭੰ ਗੁ ਰ ਪਰ੍ਸਾਿਦ ॥ ਜਪੁ ॥ ਆਿਦ ਸਚ ੁ ਜੁਗਾਿਦ ਸਚ ੁ ॥ ਹੈ ਭੀ ਸਚ ੁਨਾਨਕ ਹਸੋ ੀ ਭੀ ਸਚ ੁ ॥ ੧ ॥

In [123]:
from textblob import TextBlob

In [124]:
df['shlok_text'][1], len(df['shlok_text'][1])

('1 ੧ਓ ਸਿਤ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਿਨਰਭਉ ਿਨਰਵੈਰੁ ਅਕਾਲ ਮੂਰਿਤ ਅਜੂਨੀ ਸੈਭੰ ਗੁ ਰ ਪਰ੍ਸਾਿਦ ॥',
 75)

In [125]:
df['shlok_length'] = df['shlok_text'].apply(lambda x:len(x))
df.head()

                                                     shlok_text  shlok_length
shlok_number
1             1 ੧ਓ ਸਿਤ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਿਨਰਭਉ ਿਨਰਵੈਰੁ ਅਕਾਲ ਮੂ...            75
2                                                         ਜਪੁ ॥             5
3                                        ਆਿਦ ਸਚ ੁ ਜੁਗਾਿਦ ਸਚ ੁ ॥            22
4                                ਹੈ ਭੀ ਸਚ ੁਨਾਨਕ ਹਸੋ ੀ ਭੀ ਸਚ ੁ ॥            30
5                                                           ੧ ॥             3

In [126]:
avg_shlok_len = df['shlok_length'].sum()/len(df['shlok_text'])
avg_shlok_len

24.840792898308237

In [127]:
df['shlok_length'].iplot(kind='hist')

In [128]:
from googletrans import Translator
translator = Translator()
text = "ਸੋਚੈ ਸੋਿਚ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥	"
translated = await translator.translate(text, src='pa', dest='en')
print(translated.text)

If you think, you will not think if you think a million times.

In [129]:
async def translate_word(word, translator):
    try:
        result = await translator.translate(word, src='pa', dest='en')
        return result.text
    except:
        return ""

async def translate_df(df):
    translator = Translator()
    translations = []
    for word in df['shlok_text']:
        translations.append(await translate_word(word, translator))
    df['english'] = translations
    return df

In [130]:
df = await translate_df(df.head(10))

In [131]:
df.head(10)

,shlok_text,shlok_length,english
shlok_number,,,
1,1 ੧ਓ ਸਿਤ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਿਨਰਭਉ ਿਨਰਵੈਰੁ ਅਕਾਲ ਮੂ...,75,1 1 O Sit Namu Karta Purkhu Nirbhau Nirvairu A...
2,ਜਪੁ ॥,5,Japu
3,ਆਿਦ ਸਚ ੁ ਜੁਗਾਿਦ ਸਚ ੁ ॥,22,Aad Sach U Jugaid Sach U.
4,ਹੈ ਭੀ ਸਚ ੁਨਾਨਕ ਹਸੋ ੀ ਭੀ ਸਚ ੁ ॥,30,Hai Bhi Sach Unanak Haso Bhi Sach U.
5,੧ ॥,3,1
6,ਸੋਚੈ ਸੋਿਚ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥,33,"If you think, you will not think if you think ..."
7,ਚਪੁ ੈ ਚਪੁ ਨ ਹੋਵਈ ਜੇ ਲਾਇ ਰਹਾ ਿਲਵ ਤਾਰ ॥,37,Chapu hai chapu na hovai je lai raha liv tar ॥
8,ਭੁਿਖਆ ਭੁਖ ਨ ਉਤਰੀ ਜੇ ਬਨੰ ਾ ਪੁਰੀਆ ਭਾਰ ॥,37,"If you are hungry, you will not get enough wei..."
9,ਸਹਸ ਿਸਆਣਪਾ ਲਖ ਹੋਿਹ ਤ ਇਕ ਨ ਚਲੈ ਨਾਿਲ ॥,36,Sahas Syaanpa Lakh Hoih Te Ek Na Chalai Nil.
10,ਿਕਵ ਸਿਚਆਰਾ ਹੋਈਐ ਿਕਵ ਕੂੜੈ ਤੁਟੈ ਪਾਿਲ ॥,36,"What has been said, what rubbish you have left."

In [132]:
import nltk 
from nltk.tokenize import word_tokenize
from nltk import pos_tag
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/ihtgoot/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/ihtgoot/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [133]:
text = "ਸੋਚੈ ਸੋਿਚ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥	"
translated = await translator.translate(text, src='pa', dest='en')
words = word_tokenize(translated.text)
pos_tags = pos_tag(words)
text, translated.text ,pos_tags

('ਸੋਚੈ ਸੋਿਚ ਨ ਹੋਵਈ ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ ॥\t',
 'If you think, you will not think if you think a million times.',
 [('If', 'IN'),
  ('you', 'PRP'),
  ('think', 'VBP'),
  (',', ','),
  ('you', 'PRP'),
  ('will', 'MD'),
  ('not', 'RB'),
  ('think', 'VB'),
  ('if', 'IN'),
  ('you', 'PRP'),
  ('think', 'VBP'),
  ('a', 'DT'),
  ('million', 'CD'),
  ('times', 'NNS'),
  ('.', '.')])

In [134]:
dataset = "/home/ihtgoot/college_project/NLP_project/NEW/cleaned_shloks.csv"
df = pd.read_csv(dataset,index_col=0)
df["shlok_text"]

shlok_number
1        1 ੧ਓ ਸਿਤ ਨਾਮੁ ਕਰਤਾ ਪੁਰਖੁ ਿਨਰਭਉ ਿਨਰਵੈਰੁ ਅਕਾਲ ਮੂ...
2                                                    ਜਪੁ ॥
3                                   ਆਿਦ ਸਚ ੁ ਜੁਗਾਿਦ ਸਚ ੁ ॥
4                           ਹੈ ਭੀ ਸਚ ੁਨਾਨਕ ਹਸੋ ੀ ਭੀ ਸਚ ੁ ॥
5                                                      ੧ ॥
                               ...
86060                                                  ੧ ॥
86061                     ਖਸਟ ਰਾਗ ਉਿਨ ਗਾਏ ਸੰਿਗ ਰਾਗਨੀ ਤੀਸ ॥
86062                    ਸਭੈ ਪੁਤਰ੍ ਰਾਗੰਨ ਕੇ ਅਠਾਰਹ ਦਸ ਬੀਸ ॥
86063                                                  ੧ ॥
86064                                                  ੧ ॥
Name: shlok_text, Length: 86064, dtype: object

In [135]:
all_lines = df["shlok_text"].astype(str).tolist()
vocab = set()

for line in all_lines:
    for w in line.split():
        vocab.add(w)

vocab = list(vocab)
print("vocab size : ", len(vocab))

vocab size :  31496

In [136]:
#  normalize text 
from indicnlp.normalize.indic_normalize import IndicNormalizerFactory


def normalize_word(w):
    normalizer = IndicNormalizerFactory().get_normalizer("pa")
    return normalizer.normalize(w)

norm_vocab = [normalize_word(w) for w in vocab]

In [137]:
# Longest Common Prefix, to find stem
def lcp(a,b):
    m = min(len(a),len(b))
    for i in range(m):
        if a[i]!=b[i]:
            return a[:i]
    return a[:m]

In [138]:
from collections import Counter

def build_stems(vocab, min_prefix_len=3, min_family=4) :
    stems = Counter()
    vocab_sorted = sorted(vocab)
    for i in range(len(vocab_sorted)-1):
          w1 = vocab_sorted[i]
          w2 = vocab_sorted[i+1]
          LPC = lcp(w1,w2)
          if len(LPC)>= min_prefix_len:
            stems[LPC]+=1
    return {s for s,c in stems.items() if c >= min_family}

stems = build_stems(norm_vocab)
print("Stem count:", len(stems))

Stem count: 1683

In [139]:
def build_suffixes(vocab, stems, min_freq=4):
    suf = Counter()
    for w in vocab:
        for s in stems:
            if w.startswith(s):
                rem = w[len(s):]
                if 1 <= len(rem) <= 3:
                    suf[rem] += 1
    return {s for s,c in suf.items() if c >= min_freq}

suffixes = build_suffixes(norm_vocab, stems)
print("Suffix count:", len(suffixes))

Suffix count: 523

In [147]:
# WORD = STEM + SUFFIX
# Similarity = Levenshtein edit distance
# Lower distance = better match.

from Levenshtein import distance

def find_stem(word, stem, max_edit):
    best_stem = None
    best_score = 500

    for s in stems:
        if len(s) > len(word):
            continue
        d = distance(word[:len(s)],s)

        if d < best_score :
            best_score = d
            best_stem = s
    
    if best_score >max_edit:
        return None

    return best_stem

In [148]:
def remove_stem(word,stem):
    if word.startswith(stem):
        return word[len(stem):]
    else:
        idx = word.find(stem)
        return word[idx+len(stem):]

In [149]:
# identify suffix

def find_suffix(remainder, suffixes):
    if remainder in suffixes:
        return remainder

    for i in range(1, len(remainder)+1):
        suf = remainder[:i]
        if suf in suffixes:
            return suf

    return None

In [150]:
def segment_word(word, stems, suffixes):
    stem = find_stem(word, stems,1)
    if stem is None:
        return None

    remainder = remove_stem(word, stem)

    if remainder == "":
        return (stem, None)

    suffix = find_suffix(remainder, suffixes)

    return (stem, suffix)

In [151]:
text = df.loc[9, "shlok_text"]
words = text.split()
print(text)
translated = await translator.translate(text, src='pa', dest='en')
print(translated.text)
print("\n")
for w in words:
    print(w, "→", segment_word(w, stems, suffixes))

ਸਹਸ ਿਸਆਣਪਾ ਲਖ ਹੋਿਹ ਤ ਇਕ ਨ ਚਲੈ ਨਾਿਲ ॥
Sahas Syaanpa Lakh Hoih Te Ek Na Chalai Nil.


ਸਹਸ → ('ਸਹਸ', None)
ਿਸਆਣਪਾ → ('ਿਸਆ', 'ਣ')
ਲਖ → None
ਹੋਿਹ → ('ਹੋਿ', 'ਹ')
ਤ → None
ਇਕ → None
ਨ → None
ਚਲੈ → ('ਚਲਤ', 'ੈ')
ਨਾਿਲ → ('ਨਾਿ', 'ਲ')
॥ → None